apiVersion: v1
kind: ConfigMap
metadata:
    name: phpmyadmin-config
    namespace: phpmyadmin
data:
    k8s-config.inc.php: |
        <?php
        /* Servers configuration */
        $i = 0;
        $i++;
        $cfg['Servers'][$i]['verbose'] = 'Bookstack Server';
        $cfg['Servers'][$i]['host'] = 'mysql.bookstack.svc.cluster.local';
        $cfg['Servers'][$i]['port'] = 3306;
        $cfg['Servers'][$i]['auth_type'] = 'cookie';
        $i++;
        $cfg['Servers'][$i]['verbose'] = 'Webtrees Server';
        $cfg['Servers'][$i]['host'] = 'mysql.webtrees.svc.cluster.local';
        $cfg['Servers'][$i]['port'] = 3306;
        $cfg['Servers'][$i]['auth_type'] = 'cookie';
