apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: phpmyadmin-db-env
  namespace: phpmyadmin
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: phpmyadmin-db-env
  data:
    - secretKey: MARIADB_PASSWORD
      remoteRef:
        key: PHPMYADMIN_DB_PASSWORD
    - secretKey: MARIADB_USER
      remoteRef:
        key: PHPMYADMIN_DB_USERNAME
    - secretKey: MARIADB_DATABASE
      remoteRef:
        key: PHPMYADMIN_DB_DATABASE
