apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: phpmyadmin-app-env
  namespace: phpmyadmin
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: phpmyadmin-app-env
  data:
    - secretKey: PMA_CONTROLPASS
      remoteRef:
        key: PHPMYADMIN_DB_PASSWORD
