apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: phpmyadmin-route
  namespace: phpmyadmin
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`phpmyadmin.nathanv.app`)
      kind: Rule
      services:
        - name: phpmyadmin-service
          port: 80
      middlewares:
        - name: authentik-forward-auth
          namespace: authentik
  tls:
    certResolver: le
    domains:
      - sans:
          - "*.nathanv.app"
