apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
    name: phpmyadmin-route
    namespace: phpmyadmin

spec:
    entryPoints:
      - websecure
    routes:
      - match: Host(`phpmyadmin.nathanv.app`)
        kind: Rule
        services:
          - name: phpmyadmin-release
            port: 80
    tls:
        certResolver: le
        domains:
          - sans:
              - "*.nathanv.app"
