apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: phpmyadmin-pvc-mysql
    namespace: phpmyadmin
spec:
    storageClassName: longhorn
    accessModes:
      - ReadWriteOnce
    resources:
        requests:
            # had issues with 100 Mi
            storage: 500Mi
