apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: phpmyadmin-release
    namespace: phpmyadmin
spec:
    chart:
        spec:
            chart: phpmyadmin
            reconcileStrategy: ChartVersion
            sourceRef:
                kind: HelmRepository
                name: bitnami-repo
                namespace: common
            version: "18.1.0"
    interval: 1h0m0s
    values:
        nodeSelector:
            role: apps

        extraVolumes:
          - name: phpmyadmin-config-vol
            configMap:
                name: phpmyadmin-config

        extraVolumeMounts:
          - name: phpmyadmin-config-vol
            mountPath: /opt/bitnami/phpmyadmin/conf.d/k8s-config.inc.php
            subPath: k8s-config.inc.php
