apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reloader-release
  namespace: reloader
spec:
  releaseName: reloader
  chart:
    spec:
      chart: reloader
      sourceRef:
        kind: HelmRepository
        name: reloader-repo
        namespace: reloader
      # https://github.com/stakater/Reloader/issues/897
      version: "2.2.0"
  interval: 1h0m0s
  values:
    # registry-proxy block-start
    global:
      imageRegistry: cr.nathanv.app/ghcr.io
    # registry-proxy block-end
    reloader:
      autoReloadAll: true
      podMonitor:
        enabled: true
      deployment:
        nodeSelector:
          role: apps
