apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: reloader-release
    namespace: reloader
spec:
    releaseName: reloader
    chart:
        spec:
            chart: reloader
            sourceRef:
                kind: HelmRepository
                name: reloader-repo
                namespace: reloader
            version: "1.2.1"
    interval: 1h0m0s
    values:
        reloader:
            autoReloadAll: true
            deployment:
                nodeSelector:
                    role: apps
