apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-vip-cloud-provider-release
  namespace: kube-vip
spec:
  releaseName: kube-vip-cloud-provider
  chart:
    spec:
      chart: kube-vip-cloud-provider
      sourceRef:
        kind: HelmRepository
        name: kube-vip-repo
        namespace: kube-vip
      version: "0.2.9"
  interval: 1h0m0s
  values:
    # registry-proxy block-start
    image:
      repository: cr.nathanv.app/ghcr.io/kube-vip/kube-vip-cloud-provider
    # registry-proxy block-end
    cm:
      data:
        range-global: "10.0.1.1-10.0.1.254"
