apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-vip-release
  namespace: kube-vip
spec:
  releaseName: kube-vip
  chart:
    spec:
      chart: kube-vip
      sourceRef:
        kind: HelmRepository
        name: kube-vip-repo
        namespace: kube-vip
      version: "0.8.2"
  interval: 1h0m0s
  values:
    # registry-proxy block-start
    image:
      repository: cr.nathanv.app/ghcr.io/kube-vip/kube-vip
      # registry-proxy block-end
      # https://github.com/kube-vip/kube-vip/issues/1190
      # Only an issue in 0.9.2
      # Fixed in 1.0.0, but not published in chart yet
      tag: "v1.0.0"
    config:
      address: "10.0.1.1"
    env:
      # vip_interface: eno1
      vip_arp: "true"
      lb_enable: "true"
      lb_port: "6443"
      cp_enable: "true"
      svc_enable: "true"
      svc_election: "true"
      vip_leaderelection: "true"
      enable_node_labeling: "true"
    podMonitor:
      enabled: true
    nodeSelector:
      # don't run on wifi nodes
      connectivity: eth
