apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-secrets
  namespace: prometheus
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: alertmanager-secrets
    template:
      mergePolicy: Merge
      data:
        alertmanager.config.global.smtp_smarthost: "{{ .alertmanager_smtp_host }}:587"
  data:
    - secretKey: alertmanager.config.global.smtp_auth_password
      remoteRef:
        key: PROMETHEUS_ALERTMANAGER_SMTP_PASSWORD
    - secretKey: alertmanager.config.global.smtp_auth_username
      remoteRef:
        key: PROMETHEUS_ALERTMANAGER_SMTP_USERNAME
    - secretKey: alertmanager_smtp_host
      remoteRef:
        key: PROMETHEUS_ALERTMANAGER_SMTP_HOST
