apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-release
  namespace: prometheus
spec:
  releaseName: prometheus
  chart:
    spec:
      chart: prometheus
      sourceRef:
        kind: HelmRepository
        name: prometheus-repo
        namespace: prometheus
      version: "27.1.0"
  interval: 1h0m0s
  values:
    persistentVolume:
      storageClass: longhorn
      size: 2Gi
