apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-release
  namespace: prometheus
spec:
  releaseName: prometheus
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-repo
        namespace: prometheus
      version: "68.3.3"
  interval: 1h0m0s
  values:
    grafana:
      enabled: false
    alertmanager:
      enabled: true
    prometheus:
      prometheusSpec:
        # https://prometheus.io/docs/prometheus/latest/storage/#right-sizing-retention-size
        retention: 14d
        retentionSize: 16GB
        # https://github.com/prometheus-operator/kube-prometheus/issues/1392#issuecomment-1411719953
        ruleSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false
        probeSelectorNilUsesHelmValues: false
        # https://github.com/prometheus-operator/prometheus-operator/issues/5197#issuecomment-1382210067
        scrapeInterval: 30s
        evaluationInterval: 30s
        # https://github.com/prometheus-community/helm-charts/issues/2816#issuecomment-1356595736
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn
              # TODO maybe need to revisit
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 20Gi
