apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-release
  namespace: prometheus
spec:
  releaseName: prometheus
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-repo
        namespace: prometheus
      version: "27.1.0"
  interval: 1h0m0s
  values:
    grafana:
      enabled: false
    prometheus:
      prometheusSpec:
        storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: longhorn
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: 1Gi
    alertmanager:
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn
              accessModes: [ "ReadWriteOnce" ]
              resources:
                requests:
                  storage: 500Mi
