apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-release
  namespace: prometheus
spec:
  releaseName: prometheus
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-repo
        namespace: prometheus
      version: "79.1.0"
  interval: 1h0m0s
  values:
    grafana:
      enabled: false
    # disable the node system saturation alert
    # this constantly triggers
    defaultRules:
      disabled:
        NodeSystemSaturation: true
    alertmanager:
      enabled: true
      alertmanagerSpec:
        externalUrl: https://alertmanager.nathanv.app
        # registry-proxy block-start
        image:
          registry: cr.nathanv.app/quay.io
          # registry-proxy block-end
      config:
        global:
          smtp_from: alertmanager@nvaughn.email
          smtp_require_tls: true
        route:
          receiver: 'email-alerts'
          group_by: ['alertname', 'job']
          repeat_interval: 6h
        receivers:
          # https://github.com/prometheus-community/helm-charts/issues/4068#issuecomment-1848626909
          # I wasted an hour on this
          - name: 'null'
          # ^^^ MUST KEEP ^^^
          - name: 'email-alerts'
            email_configs:
              - to: 'nvaughn51@gmail.com'
                send_resolved: true
    # https://github.com/SovereignCloudStack/k8s-observability/issues/48#issuecomment-2051128705
    # if i ever want to revisit this
    kubeControllerManager:
      enabled: false
    kubeEtcd:
      enabled: false
    kubeProxy:
      enabled: false
    kubeScheduler:
      enabled: false
    prometheus:
      prometheusSpec:
        # registry-proxy block-start
        image:
          registry: cr.nathanv.app/quay.io
        # registry-proxy block-end
        externalUrl: https://prometheus.nathanv.app
        nodeSelector:
          role: apps
        # https://prometheus.io/docs/prometheus/latest/storage/#right-sizing-retention-size
        retention: 14d
        retentionSize: 16GB
        # https://github.com/prometheus-operator/kube-prometheus/issues/1392#issuecomment-1411719953
        ruleSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false
        probeSelectorNilUsesHelmValues: false
        # try to limit to 1 container
        replicas: 1
        shards: 1
        # https://github.com/prometheus-operator/prometheus-operator/issues/5197#issuecomment-1382210067
        scrapeInterval: 30s
        evaluationInterval: 30s
        # https://github.com/prometheus-community/helm-charts/issues/2816#issuecomment-1356595736
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn
              # NFS shares cause problems
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 20Gi
    # registry-proxy block-start
    crds:
      upgradeJob:
        image:
          busybox:
            registry: cr.nathanv.app/docker.io
          kubectl:
            registry: cr.nathanv.app/registry.k8s.io
    prometheusOperator:
      image:
        registry: cr.nathanv.app/quay.io
      thanosImage:
        registry: cr.nathanv.app/quay.io
      admissionWebhooks:
        deployment:
          image:
            registry: cr.nathanv.app/quay.io
        patch:
          image:
            registry: cr.nathanv.app/registry.k8s.io
      prometheusConfigReloader:
        image:
          registry: cr.nathanv.app/quay.io
    thanosRuler:
      thanosRulerSpec:
        image:
          registry: cr.nathanv.app/quay.io
    prometheus-node-exporter:
      image:
        registry: cr.nathanv.app/quay.io
    kube-state-metrics:
      image:
        registry: cr.nathanv.app/registry.k8s.io
        # registry-proxy block-end
  valuesFrom:
    - kind: Secret
      name: alertmanager-secrets
      valuesKey: alertmanager.config.global.smtp_smarthost
      targetPath: alertmanager.config.global.smtp_smarthost
    - kind: Secret
      name: alertmanager-secrets
      valuesKey: alertmanager.config.global.smtp_auth_username
      targetPath: alertmanager.config.global.smtp_auth_username
    - kind: Secret
      name: alertmanager-secrets
      valuesKey: alertmanager.config.global.smtp_auth_password
      targetPath: alertmanager.config.global.smtp_auth_password
