apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: octoprint-deployment
  namespace: octoprint
spec:
  replicas: 1
  serviceName: octoprint
  selector:
    matchLabels:
      app: octoprint
  template:
    metadata:
      labels:
        app: octoprint
    spec:
      nodeSelector:
        hardware: 3dprinter
      containers:
        - env:
            - name: ENABLE_MJPG_STREAMER
              value: "true"
          image: docker.io/octoprint/octoprint:1.10.3
          name: octoprint
          securityContext:
            privileged: true # for access to the printer and webcame
          ports:
            - containerPort: 8080 # webcam
            - containerPort: 80 # http server
          volumeMounts:
            - mountPath: /octoprint
              name: data-vol
      volumes:
        - name: data-vol
          persistentVolumeClaim:
            claimName: octoprint-pvc
