apiVersion: nathanv.me/v1
kind: DNSConfig
metadata:
  name: octoprint-cam-dns-config
  namespace: octoprint
spec:
  hostname: octoprint-cam.nathanv.app
  internalCNAME: reverse-proxy.svc.nathanv.home
  # externalCNAME: tunnel.nathanv.app
