apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: octoprint-pvc
  namespace: octoprint
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
