apiVersion: nathanv.me/v1
kind: DNSConfig
metadata:
  name: harbor-dns-config
  namespace: harbor
spec:
  hostname: cr.nathanv.app
  internalCNAME: reverse-proxy.svc.nathanv.home
  externalCNAME: tunnel.nathanv.app
