apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-secrets-external
  namespace: harbor
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: harbor-secrets
  data:
    - secretKey: database.internal.password
      remoteRef:
        key: HARBOR_DB_PASSWORD
    - secretKey: harborAdminPassword
      remoteRef:
        key: HARBOR_ADMIN_PASSWORD
    - secretKey: registry.credentials.password
      remoteRef:
        key: HARBOR_REGISTRY_PASSWORD
