apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: omada-deployment
  namespace: omada
spec:
  replicas: 1
  serviceName: omada
  selector:
    matchLabels:
      app: omada
  template:
    metadata:
      labels:
        app: omada
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                # when possible, run on the network controller
                matchExpressions:
                  - key: role
                    operator: In
                    values:
                      - network
      initContainers:
        - name: permission-fix
          image: docker.io/library/busybox:1.37.0
          command: ['sh', '-c']
          args: ['chown -R 508:508 /opt/tplink/EAPController/']
          volumeMounts:
            - mountPath: /opt/tplink/EAPController/data
              name: omada-vol-data
            - mountPath: /opt/tplink/EAPController/logs
              name: omada-vol-logs
      containers:
        - env:
            - name: PUID
              value: "508"
            - name: PGID
              value: "508"
            - name: TZ
              value: "America/Chicago"
          image: docker.io/mbentley/omada-controller:5.15.8.2
          name: omada
          ports:
            - containerPort: 8088
              protocol: TCP
              name: manage_http_port
            - containerPort: 8043
              protocol: TCP
              name: manage_https_port
            - containerPort: 8843
              protocol: TCP
              name: portal_https_port
            - containerPort: 29812
              protocol: TCP
              name: port_adopt_v1
            - containerPort: 27001
              protocol: UDP
              name: port_app_discovery
            - containerPort: 29810
              protocol: UDP
              name: port_discovery
            - containerPort: 29811
              protocol: TCP
              name: port_manager_v1
            - containerPort: 29814
              protocol: TCP
              name: port_manager_v2
            - containerPort: 29815
              protocol: TCP
              name: port_transfer_v2
            - containerPort: 29816
              protocol: TCP
              name: port_rtty
            - containerPort: 29813
              protocol: TCP
              name: port_upgrade_v1
          volumeMounts:
            - mountPath: /opt/tplink/EAPController/data
              name: omada-vol-data
            - mountPath: /opt/tplink/EAPController/logs
              name: omada-vol-logs
      volumes:
        - name: omada-vol-data
          persistentVolumeClaim:
            claimName: omada-pvc-data
        - name: omada-vol-logs
          persistentVolumeClaim:
            claimName: omada-pvc-logs
