apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: omada-route
  namespace: omada
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`omada.nathanv.app`)
      kind: Rule
      services:
        - name: omada-service
          port: 8043
          scheme: https
          # required as omada requires ssl
          serversTransport: omada-transport
          # internal only
          # middlewares:
          #   - name: authentik-forward-auth
          #     namespace: authentik
  tls:
    certResolver: le
    domains:
      - sans:
          - "*.nathanv.app"
