apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: omada-pvc-logs
    namespace: omada
spec:
    storageClassName: longhorn
    accessModes:
      - ReadWriteOnce
    resources:
        requests:
            storage: 5Gi
