apiVersion: v1
kind: Service
metadata:
  name: omada-service
  namespace: omada
spec:
  type: LoadBalancer
  loadBalancerIP: "10.0.1.6"
  selector:
    app: omada
  ports:
    # https://github.com/mbentley/docker-omada-controller?tab=readme-ov-file#optional-variables
    - port: 8088
      protocol: TCP
      name: manage-http-port
    - port: 8043
      protocol: TCP
      name: manage-https-port
    - port: 8843
      protocol: TCP
      name: portal-https-port
    - port: 29812
      protocol: TCP
      name: port-adopt-v1
    - port: 27001
      protocol: UDP
      name: port-app-discovery
    - port: 29810
      protocol: UDP
      name: port-discovery
    - port: 29811
      protocol: TCP
      name: port-manager-v1
    - port: 29814
      protocol: TCP
      name: port-manager-v2
    - port: 29815
      protocol: TCP
      name: port-transfer-v2
    - port: 29816
      protocol: TCP
      name: port-rtty
    - port: 29813
      protocol: TCP
      name: port-upgrade-v1
