apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: technitium-dns-route
  namespace: technitium-dns
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`technitium-dns.nathanv.app`)
      kind: Rule
      services:
        - name: technitium-dns-service
          port: 5380
      middlewares:
        - name: authentik-forward-auth
          namespace: authentik
  tls:
    certResolver: le
    domains:
      - sans:
          - "*.nathanv.app"
