apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: technitium-dns-pvc-config
  namespace: technitium-dns
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
