apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: technitium-dns-pvc-config
  namespace: technitium-dns
spec:
  storageClassName: longhorn-rwx
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
