apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: technitium-dns-env
  namespace: technitium-dns
spec:
  encryptedData:
    MARIADB_PASSWORD: AgBuMw/4S+IMF4FjvfhG+PI6I/1N6+LP6p5NaCzNvXEA34ULMBLGLiIqkf7vX7PB9aiVBTCIbf3+meigCT6oTVIgWZSayeOev+eHLymSdfLzqQMTiz6S+dTs4Jlg8P2eI/oT1NDhFTFkC3cv/vOARldv0KyHFN6qEU+1Fr5YkVF0juo+oee6E7OyJ/h0lAZIvcf0DWaubvXDVj2mhrbDWrrrR9/pFLPvk4KbALBbV555U71PmHZi+8eEdgbnwbB2ONPnFCrX4lQMbw4c9jaZm/jFkdQRcv/kNaWUOpbFiHeTt/1GzOhN5dv+rV1ISqLEMonb/8XsmOhMwhYOXqKztCdWPZ0CA4t6+jO2Ryivp11sUvj0jldJd+/o+AFYAxTL1ltWwBsmc/DRploy/UzAV9kMOVExGS9yUnAsWVWbfOWSvSMo19rIAewCQ6yIMvBWYkEtTZfeSEZFgb6fTpglOetuQhy6xX3fPTf7Jsr+GddIAXvQrv3GtvEu9P9P2QZIVt1eShrb+fZ8Rcg+A1a4oUHRMwxjPvp1s57dkCbfZxnp0FzKdapNIAv2Z2KQlI766zqhefRXP9rXGeds2xtj1Wr/HD+kAybiib6g1ay8jXVls6vsXG+VQRHzxsSP3QndH/vWPAaDkXMJiCALIwdsBuJ4sF/gywiNpAMgxfi7p4iATSPeTRgpknY7hMLfZ3doYUwJ79ABWzrdaYz/roHNDANQcWytxmfkVHBqtCA71Hc3Z8qXzzo=
  template:
    metadata:
      creationTimestamp: null
      name: technitium-dns-env
      namespace: technitium-dns
