apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: technitium-dns-env
  namespace: technitium-dns
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgC2QwbawLF1v8YhHdxhnYUDVR8R57VXUUz5OAKvmCY5wBDGIoHQmCkQJXg9hbJzawcboFfX63LYrJdTk1zM63XCHpOy/RcLKPJcFTShyfpQM8WPvInKi/zg56RW2kNUfRpFyuIEYB6sLb6mNiipzj0UbFD/Rc+1KUhuZ+o6ZkB2JzkRvdzN1UyEfhvVQiJzb1GQBtl0Q6/XTQou+8E+gchmmc4NSTClWpZB+dexGd4DWM/7C1EktdSldepMffw2BPVY9kUfa3CBoTETvv0fZ3a8PsCAIBrWEnRtJ5Gj4j4qCqChvxaLRaPef1h3fLEzXob28FjbM0HUot9FSvuEkwUtM+qcmESK0nKhuyadVoZapEyBAS7sXJop2xnxtYlWfTk7g8hh5lN0KH9f1IhftWnKKboIvurmOT9snqGLg8ECE8u1JyXn8W75uO1lM77kOr5bGPw02lfyui8CGbs2mkBUsSjPkCtDoHJ6O2WefmYf13U/3ylYMwmF9zKjn1wg9Lno7OuakaD0/t54plRmNrOyHh6R6AM+RBpK5tQWWceG0v7xtRxlovZKpn4ot3bQVYmlvZ6zySp9NOfO5t4//zOy0kUjC3LkkwKHbzFMACe8JRhT6wzbSR/FsqyeelJbONHgunTJ5UQaZkB5cWb+mKgGIy3nBgSLqusO3Qfwh/rz7h6YubeUFbX4Jvknt5k631w/mq5jfVXVJMW00dYa2uenW6ucpl7i16g03FaVTn91bjhjroY=
  template:
    metadata:
      name: technitium-dns-env
      namespace: technitium-dns
