apiVersion: nathanv.me/v1
kind: DNSConfig
metadata:
  name: mediacms-dns-config
  namespace: mediacms
spec:
  hostname: videos.nathanv.app
  internalCNAME: reverse-proxy.svc.nathanv.home
  # externalCNAME: tunnel.nathanv.app
