apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mediacms-app-env-external
  namespace: mediacms
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: mediacms-app-env
  data:
    - secretKey: ADMIN_EMAIL
      remoteRef:
        key: MEDIACMS_ADMIN_EMAIL
    - secretKey: ADMIN_PASSWORD
      remoteRef:
        key: MEDIACMS_ADMIN_PASSWORD
    - secretKey: ADMIN_USER
      remoteRef:
        key: MEDIACMS_ADMIN_USERNAME
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: MEDIACMS_DB_PASSWORD
    - secretKey: POSTGRES_USER
      remoteRef:
        key: MEDIACMS_DB_USERNAME
    - secretKey: POSTGRES_DB
      remoteRef:
        key: MEDIACMS_DB_DATABASE
    - secretKey: SECRET_KEY
      remoteRef:
        key: MEDIACMS_SECRET_KEY
    - secretKey: EMAIL_HOST
      remoteRef:
        key: MEDIACMS_SMTP_HOST
    - secretKey: EMAIL_HOST_USER
      remoteRef:
        key: MEDIACMS_SMTP_USERNAME
    - secretKey: EMAIL_HOST_PASSWORD
      remoteRef:
        key: MEDIACMS_SMTP_PASSWORD
