apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediacms-pvc-media
  namespace: mediacms
spec:
  storageClassName: longhorn-rwx
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
