apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediacms-pvc-redis
  namespace: mediacms
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
