apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: omada-exporter-env
  namespace: omada
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: omada-exporter-env
  data:
    - secretKey: OMADA_CLIENT_ID
      remoteRef:
        key: OMADA_EXPORTER_CLIENT_ID
    - secretKey: OMADA_PASS
      remoteRef:
        key: OMADA_EXPORTER_PASSWORD
    - secretKey: OMADA_SECRET_ID
      remoteRef:
        key: OMADA_EXPORTER_SECRET_ID
    - secretKey: OMADA_USER
      remoteRef:
        key: OMADA_EXPORTER_USERNAME
