apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: omada-exporter-release
  namespace: omada
spec:
  releaseName: omada-exporter
  chart:
    spec:
      chart: omada-exporter
      sourceRef:
        kind: HelmRepository
        name: omada-exporter-repo
        namespace: omada
      version: "0.10.0"
  interval: 1h0m0s
  values:
    nodeSelector:
      role: apps
    omada:
      host: https://omada.nathanv.app/
      insecure: true
      site: Home
      username: prometheus
  valuesFrom:
    - kind: Secret
      name: omada-exporter-secrets
      valuesKey: omada.password
      targetPath: omada.password
