apiVersion: v1
kind: Service
metadata:
  name: omada-exporter-service
  namespace: omada
spec:
  type: ClusterIP
  selector:
    app: omada-exporter
  ports:
    - port: 9202
      targetPort: metrics
      protocol: TCP
      name: metrics
