apiVersion: v1
kind: Service
metadata:
  name: omada-exporter-service
  namespace: omada
  labels:
    app: omada-exporter
spec:
  type: ClusterIP
  selector:
    app: omada-exporter
  ports:
    - port: 9202
      protocol: TCP
