apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: traefik-cf-token-external
  namespace: traefik
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: traefik-cf-token
  data:
    - secretKey: CF_DNS_API_TOKEN
      remoteRef:
        key: TRAEFIK_CLOUDFLARE_API_TOKEN
