apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-release
  namespace: traefik
spec:
  # https://github.com/fluxcd/flux2/issues/5052#issuecomment-2450931227
  install:
    disableWait: true
  upgrade:
    disableWait: true
  rollback:
    disableWait: true
  releaseName: traefik
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik-repo
        namespace: traefik
      version: "36.3.0"
  interval: 1h0m0s
  values:
    # registry-proxy block-start
    image:
      registry: cr.nathanv.app/docker.io
    # registry-proxy block-end
    persistence:
      enabled: true
      storageClass: longhorn
      accessMode: ReadWriteMany
    service:
      type: LoadBalancer
      spec:
        loadBalancerIP: "10.0.1.2"
    certificatesResolvers:
      le:
        acme:
          email: nath@nvaughn.email
          storage: /data/acme.json
          dnsChallenge:
            provider: cloudflare
            resolvers:
              # i block 8.8.8.8 on my network
              - "1.1.1.1:53"
              - "9.9.9.9:53"
    providers:
      kubernetesCRD:
        enabled: true
        # required for authentik
        allowCrossNamespace: true
    # kubectl -n traefik port-forward $(kubectl -n traefik get pods --selector "app.kubernetes.io/name=traefik" --output=name | head -n 1) 8080:8080
    ingressRoute:
      dashboard:
        enabled: true
    metrics:
      prometheus:
        service:
          enabled: true
        serviceMonitor:
          enabled: true
    ports:
      websecure:
        tls:
          certResolver: le
    envFrom:
      - secretRef:
          name: traefik-cf-token
    # https://github.com/traefik/traefik-helm-chart/blob/master/EXAMPLES.md#use-traefik-native-lets-encrypt-integration-without-cert-manager
    # https://github.com/traefik/traefik-helm-chart/issues/396#issuecomment-1873454777
    deployment:
      replicas: 2
      initContainers:
        - name: volume-permissions
          # registry-proxy image-prefix
          image: cr.nathanv.app/docker.io/library/busybox:1.37.0
          command: ["sh", "-c", "ls -la /; touch /data/acme.json; chmod -v 600 /data/acme.json"]
          volumeMounts:
            - mountPath: /data
              name: data
          securityContext:
            runAsNonRoot: true
            runAsGroup: 65532
            runAsUser: 65532
    podSecurityContext:
      fsGroup: 65532
      fsGroupChangePolicy: "OnRootMismatch"
    nodeSelector:
      role: apps
