apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-release
  namespace: traefik
spec:
  releaseName: traefik
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik-repo
        namespace: traefik
      version: "33.0.0"
  interval: 1h0m0s
  values:
    persistence:
      enabled: true
    certificatesResolvers:
      le:
        acme:
          email: nvaughn51@gmail.com
          storage: /data/acme.json
          dnsChallenge:
            provider: cloudflare
            resolvers:
              # i block 8.8.8.8 on my network
              - "1.1.1.1:53"
              - "9.9.9.9:53"
    envFrom:
      - secretRef:
          name: traefik-cf-token
    nodeSelector:
      role: apps