apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-release
  namespace: traefik
spec:
  releaseName: traefik
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik-repo
        namespace: traefik
      version: "33.1.0"
  interval: 1h0m0s
  values:
    persistence:
      enabled: true
      storageClass: longhorn
    service:
      type: LoadBalancer
      spec:
        loadBalancerIP: "10.0.1.2"
    certificatesResolvers:
      le:
        acme:
          email: nvaughn51@gmail.com
          storage: /data/acme.json
          dnsChallenge:
            provider: cloudflare
            resolvers:
            # i block 8.8.8.8 on my network
            - "1.1.1.1:53"
            - "9.9.9.9:53"
    ports:
      websecure:
        tls:
          certResolver: le
    envFrom:
    - secretRef:
        name: traefik-cf-token
    # https://github.com/traefik/traefik-helm-chart/blob/master/EXAMPLES.md#use-traefik-native-lets-encrypt-integration-without-cert-manager
    # https://github.com/traefik/traefik-helm-chart/issues/396#issuecomment-1873454777
    deployment:
      initContainers:
      - name: volume-permissions
        image: docker.io/library/busybox:latest
        command: [ "sh", "-c", "ls -la /; touch /data/acme.json; chmod -v 600 /data/acme.json" ]
        volumeMounts:
        - mountPath: /data
          name: data
        securityContext:
          runAsNonRoot: true
          runAsGroup: 65532
          runAsUser: 65532
    podSecurityContext:
      fsGroup: 65532
      fsGroupChangePolicy: "OnRootMismatch"
    nodeSelector:
      role: apps
