apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless-tika-deployment
  namespace: paperless
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paperless-tika
  template:
    metadata:
      labels:
        app: paperless-tika
    spec:
      nodeSelector:
        role: apps
      containers:
        - image: docker.io/apache/tika:3.1.0.0
          name: tika
          ports:
            - containerPort: 9998
