apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-db-env-external
  namespace: paperless
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: paperless-db-env
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: PAPERLESS_DB_PASSWORD
    - secretKey: POSTGRES_USER
      remoteRef:
        key: PAPERLESS_DB_USERNAME
    - secretKey: POSTGRES_DB
      remoteRef:
        key: PAPERLESS_DB_DATABASE
