apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-app-env
  namespace: paperless
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: paperless-app-env
    template:
      mergePolicy: Merge
      data:
        PAPERLESS_SOCIALACCOUNT_PROVIDERS: >-
          {"openid_connect":{"APPS":[{"provider_id":"authentik","name":"Authentik","client_id":"{{ .OIDC_CLIENT_ID }}","secret":"{{ .OIDC_CLIENT_SECRET }}","settings":{"server_url":"https://authentik.nathanv.app/application/o/paperless/.well-known/openid-configuration"}}],"OAUTH_PKCE_ENABLED":"True"}}
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: PAPERLESS_DB_PASSWORD
    - secretKey: PAPERLESS_DBPASS
      remoteRef:
        key: PAPERLESS_DB_PASSWORD
    - secretKey: PAPERLESS_DBUSER
      remoteRef:
        key: PAPERLESS_DB_USERNAME
    - secretKey: POSTGRES_USER
      remoteRef:
        key: PAPERLESS_DB_USERNAME
    - secretKey: PAPERLESS_DBNAME
      remoteRef:
        key: PAPERLESS_DB_DATABASE
    - secretKey: POSTGRES_DB
      remoteRef:
        key: PAPERLESS_DB_DATABASE
    - secretKey: PAPERLESS_SECRET_KEY
      remoteRef:
        key: PAPERLESS_SECRET_KEY
    - secretKey: PAPERLESS_EMAIL_HOST
      remoteRef:
        key: PAPERLESS_SMTP_HOST
    - secretKey: PAPERLESS_EMAIL_HOST_USER
      remoteRef:
        key: PAPERLESS_SMTP_USERNAME
    - secretKey: PAPERLESS_EMAIL_HOST_PASSWORD
      remoteRef:
        key: PAPERLESS_SMTP_PASSWORD
    - secretKey: OIDC_CLIENT_ID
      remoteRef:
        key: PAPERLESS_OIDC_CLIENT_ID
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: PAPERLESS_OIDC_CLIENT_SECRET
