apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-pvc-media
  namespace: paperless
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
