apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-pvc-data
  namespace: paperless
spec:
  storageClassName: longhorn-rwx
  accessModes:
    # Lockfiles on NFS don't work well, must be on a single reader storage path
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
