apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-pvc-data
  namespace: paperless
spec:
  storageClassName: longhorn-rwx
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
