apiVersion: descheduler/v1alpha2
kind: DeschedulerPolicy
metadata:
  name: descheduler-policy
  namespace: descheduler
strategies:
  RemovePodsViolatingNodeAffinity:
    enabled: true
    params:
      nodeAffinityType:
      - preferredDuringSchedulingIgnoredDuringExecution