apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: descheduler-release
  namespace: descheduler
spec:
  releaseName: descheduler
  chart:
    spec:
      chart: descheduler
      sourceRef:
        kind: HelmRepository
        name: descheduler-repo
        namespace: descheduler
      version: "0.36.0"
  interval: 1h0m0s
  values:
    # registry-proxy block-start
    image:
      repository: cr.nathanv.app/registry.k8s.io/descheduler/descheduler
    # registry-proxy block-end
    nodeSelector:
      role: apps
    # override policy
    deschedulerPolicy:
      profiles:
      - name: Remove Pods Violating Node Affinity
        pluginConfig:
        - name: RemovePodsViolatingNodeAffinity
          args:
            nodeAffinityType:
            - requiredDuringSchedulingIgnoredDuringExecution
            - preferredDuringSchedulingIgnoredDuringExecution
        plugins:
          deschedule:
            enabled:
              - RemovePodsViolatingNodeAffinity
