apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-mysql-deployment
  namespace: ghost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost-mysql
  template:
    metadata:
      labels:
        app: ghost-mysql
    spec:
      nodeSelector:
        role: apps
      securityContext:
        fsGroup: 999
        runAsUser: 999
        runAsGroup: 999
      # initContainers:
      # - name: permission-fix
      #   image: docker.io/library/busybox:latest
      #   command: [ 'sh', '-c' ]
      #   args: [ 'chown -R 999:999 /var/lib/mysql' ]
      #   volumeMounts:
      #   - mountPath: /var/lib/mysql
      #     name: mysql-vol
      containers:
      # https://ghost.org/docs/faq/supported-databases/
      # - command: [ mysqld, '--character-set-server=utf8mb4', '--collation-server=utf8mb4_0900_ai_ci' ]
      - env:
        - name: MYSQL_RANDOM_ROOT_PASSWORD
          value: "1"
        - name: MYSQL_USER
          value: ghost
        - name: MYSQL_DATABASE
          value: ghost
        envFrom:
        - secretRef:
            name: ghost-env
        # https://ghost.org/docs/faq/supported-databases/
        image: docker.io/library/mysql:8.4.3
        name: mysql
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-vol
      volumes:
      - name: mysql-vol
        persistentVolumeClaim:
          claimName: ghost-pvc-mysql
