apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghost-app-env
  namespace: ghost
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: ghost-app-env
  data:
    - secretKey: database__connection__password
      remoteRef:
        key: GHOST_DB_PASSWORD
    - secretKey: database__connection__user
      remoteRef:
        key: GHOST_DB_USERNAME
    - secretKey: database__connection__database
      remoteRef:
        key: GHOST_DB_DATABASE
    - secretKey: mail__options__auth__pass
      remoteRef:
        key: GHOST_SMTP_PASSWORD
    - secretKey: mail__options__auth__user
      remoteRef:
        key: GHOST_SMTP_USERNAME
    - secretKey: mail__options__host
      remoteRef:
        key: GHOST_SMTP_HOST
