apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghost-db-env-external
  namespace: ghost
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: ghost-db-env
  data:
    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: GHOST_DB_PASSWORD
    - secretKey: MYSQL_USER
      remoteRef:
        key: GHOST_DB_USERNAME
    - secretKey: MYSQL_DATABASE
      remoteRef:
        key: GHOST_DB_DATABASE
