apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ghost-route
  namespace: ghost
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`christmas.nathanv.app`)
      kind: Rule
      services:
        - name: ghost-service
          port: 2368
  tls:
    certResolver: le
    domains:
      - sans:
          - "*.nathanv.app"
