apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: ghost-pvc-mysql
    namespace: ghost
spec:
    storageClassName: longhorn
    accessModes:
      - ReadWriteOnce
    resources:
        requests:
            storage: 5Gi
