apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-pkgs-deployment
  namespace: git-pkgs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: git-pkgs
  template:
    metadata:
      labels:
        app: git-pkgs
    spec:
      nodeSelector:
        role: apps
      containers:
        - env:
            - name: PROXY_BASE_URL
              value: "https://pkgs.nathanv.app"
            - name: PROXY_UI_URL
              value: "https://pkgs-ui.nathanv.app"
            - name: PROXY_DATABASE_DRIVER
              value: postgres
            - name: PROXY_STORAGE_MAX_SIZE
              value: 10GB
          envFrom:
            - secretRef:
                name: git-pkgs-env
          # registry-proxy image-prefix
          image: cr.nathanv.app/ghcr.io/git-pkgs/proxy:v0.7.0
          name: git-pkgs
          ports:
            - containerPort: 8080
