apiVersion: nathanv.me/v1
kind: DNSConfig
metadata:
  name: git-pkgs-dns-config-ui
  namespace: git-pkgs
spec:
  hostname: pkgs-ui.nathanv.app
  internalCNAME: reverse-proxy.svc.nathanv.home
  externalCNAME: tunnel.nathanv.app
