apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: git-pkgs-db-env-external
  namespace: git-pkgs
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: git-pkgs-db-env
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: GIT_PKGS_DB_USERNAME
    - secretKey: POSTGRES_DB
      remoteRef:
        key: GIT_PKGS_DB_DATABASE
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: GIT_PKGS_DB_PASSWORD
