apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: git-pkgs-app-env-external
  namespace: git-pkgs
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: git-pkgs-app-env
    template:
      mergePolicy: Merge
      data:
        PROXY_DATABASE_URL: "postgres://{{ .POSTGRES_USER }}:{{ .POSTGRES_PASSWORD }}@git-pkgs-postgresql-service.git-pkgs.svc.cluster.local:5432/{{ .POSTGRES_DB }}?sslmode=disable"
        PROXY_STORAGE_URL: "s3://{{ .S3_BUCKET }}?endpoint={{ .S3_ENDPOINT }}&prefix=pkgs/&use_path_style=false"
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: GIT_PKGS_S3_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: GIT_PKGS_S3_SECRET_ACCESS_KEY
    - secretKey: AWS_REGION
      remoteRef:
        key: GIT_PKGS_S3_REGION
    - secretKey: S3_ENDPOINT
      remoteRef:
        key: GIT_PKGS_S3_ENDPOINT
    - secretKey: S3_BUCKET
      remoteRef:
        key: GIT_PKGS_S3_BUCKET
    - secretKey: POSTGRES_USER
      remoteRef:
        key: GIT_PKGS_DB_USERNAME
    - secretKey: POSTGRES_DB
      remoteRef:
        key: GIT_PKGS_DB_DATABASE
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: GIT_PKGS_DB_PASSWORD
