apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: git-pkgs-route
  namespace: git-pkgs
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`pkgs.nathanv.app`)
      kind: Rule
      services:
        - name: git-pkgs-service
          port: 8080
    - match: Host(`pkgs.nathanv.app`) && (PathPrefix(`/ui`) || PathPrefix(`/api`) || PathPrefix(`/health`) || PathPrefix(`/stats`) || PathPrefix(`/metrics`))
      kind: Rule
      services:
        - name: git-pkgs-service
          port: 8080
      middlewares:
        - name: authentik-forward-auth
          namespace: authentik
  tls:
    certResolver: le
    domains:
      - sans:
          - "*.nathanv.app"
