apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: git-pkgs-pvc-postgresql
  namespace: git-pkgs
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
