apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: scrutiny-collector-daemonset
  namespace: scrutiny
spec:
  # tolerations:
  #   # these tolerations are to have the daemonset runnable on control plane nodes
  #   # remove them if your control plane nodes should not run pods
  #   - key: node-role.kubernetes.io/control-plane
  #     operator: Exists
  #     effect: NoSchedule
  #   - key: node-role.kubernetes.io/master
  #     operator: Exists
  #     effect: NoSchedule
  selector:
    matchLabels:
      app: scrutiny-collector
  template:
    metadata:
      annotations:
        container.apparmor.security.beta.kubernetes.io/scrutiny-collector: unconfined
      labels:
        app: scrutiny-collector
    spec:
      containers:
      - name: scrutiny-collector
        image: ghcr.io/analogj/scrutiny:v0.8.1-collector
        env:
        - name: COLLECTOR_API_ENDPOINT
          value: http://scrutiny-web-service.scrutiny.svc.cluster.local:8080
        - name: COLLECTOR_HOST_ID
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: udev
          mountPath: /run/udev
          readOnly: true
        - name: dev-nvme0n1
          mountPath: /dev/nvme0n1
          readOnly: true
        securityContext:
          capabilities:
            add: [ "SYS_RAWIO", "SYS_ADMIN", "CAP_SYS_PTRACE", "DAC_OVERRIDE" ]
      resources:
        limits:
          devices: /dev/nvme0n1
      volumes:
      - name: udev
        hostPath:
          path: /run/udev
      - name: dev-nvme0n1
        hostPath:
          path: /dev/nvme0n1
