apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: scrutiny-influxdb-pvc
    namespace: scrutiny
spec:
    storageClassName: longhorn
    accessModes:
      - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
