apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scrutiny-web-pvc
  namespace: scrutiny
spec:
  storageClassName: longhorn-rwx
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi
