apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-deployment
  namespace: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      nodeSelector:
        role: apps
      initContainers:
        - name: permission-fix
          # registry-proxy image-prefix
          image: cr.nathanv.app/docker.io/library/busybox:1.37.0
          command: ['sh', '-c']
          # https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html#environment-variables
          args: ['chown -R 5050:5050 /var/lib/pgadmin']
          volumeMounts:
            - mountPath: /var/lib/pgadmin
              name: pgadmin-vol-data
      containers:
        - env:
            - name: PGADMIN_CONFIG_AUTO_DISCOVER_SERVERS
              value: "False"
            - name: PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED
              value: "True"
            - name: PGADMIN_CONFIG_MAIL_PORT
              value: "587"
            - name: PGADMIN_CONFIG_MAIL_USE_TLS
              value: "True"
            - name: PGADMIN_CONFIG_SECURITY_EMAIL_SENDER
              value: '"pgadmin@nvaughn.email"'
            - name: PGADMIN_CONFIG_AUTHENTICATION_SOURCES
              # value: '["oauth2", "internal"]'
              value: '["oauth2"]'
          envFrom:
            - secretRef:
                name: pgadmin-env
          # registry-proxy image-prefix
          image: cr.nathanv.app/docker.io/dpage/pgadmin4:9.4
          name: pgadmin
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /var/lib/pgadmin
              name: pgadmin-vol-data
            - mountPath: /pgadmin4/config_local.py
              name: pgadmin-vol-oauth
              subPath: config_local.py
              readOnly: true
      volumes:
        - name: pgadmin-vol-data
          persistentVolumeClaim:
            claimName: pgadmin-pvc-data
        - name: pgadmin-vol-oauth
          secret:
            secretName: pgadmin-oauth
