apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgadmin-oauth
  namespace: pgadmin
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: pgadmin-oauth
    template:
      mergePolicy: Replace
      data:
        config_local.py: |
          OAUTH2_CONFIG = [
              {
                  "OAUTH2_NAME": "authentik",
                  "OAUTH2_DISPLAY_NAME": "Authentik",
                  "OAUTH2_CLIENT_ID": "{{ .OIDC_CLIENT_ID }}",
                  "OAUTH2_CLIENT_SECRET": "{{ .OIDC_CLIENT_SECRET }}",
                  "OAUTH2_TOKEN_URL": "https://authentik.nathanv.app/application/o/token/",
                  "OAUTH2_AUTHORIZATION_URL": "https://authentik.nathanv.app/application/o/authorize/",
                  "OAUTH2_SERVER_METADATA_URL": "https://authentik.nathanv.app/application/o/pgadmin/.well-known/openid-configuration",
                  "OAUTH2_API_BASE_URL": "https://authentik.nathanv.app",
                  "OAUTH2_USERINFO_ENDPOINT": "https://authentik.nathanv.app/application/o/userinfo/",
                  "OAUTH2_SCOPE": "openid email profile name",
                  "OAUTH2_USERNAME_CLAIM": "email",
                  "OAUTH2_ICON": "fa-hive",
                  "OAUTH2_BUTTON_COLOR": "#0000ff",
                  "OAUTH2_ADDITIONAL_CLAIMS": None,
                  "OAUTH2_SSL_CERT_VERIFICATION": True,
                  "OAUTH2_LOGOUT_URL": "https://authentik.nathanv.app/application/o/pgadmin/end-session/",
              }
          ]
  data:
    - secretKey: OIDC_CLIENT_ID
      remoteRef:
        key: PGADMIN_OIDC_CLIENT_ID
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: PGADMIN_OIDC_CLIENT_SECRET
