apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgadmin-app-env-external
  namespace: pgadmin
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: pgadmin-app-env
    template:
      mergePolicy: Merge
      data:
        PGADMIN_CONFIG_CONFIG_DATABASE_URI: "'postgresql://{{ .POSTGRES_USER }}:{{ .POSTGRES_PASSWORD }}@pgadmin-postgresql-service.pgadmin.svc.cluster.local:5432/{{ .POSTGRES_DB }}'"
        PGADMIN_CONFIG_MAIL_SERVER: "'{{ .PGADMIN_SMTP_HOST }}'"
        PGADMIN_CONFIG_MAIL_USERNAME: "'{{ .PGADMIN_SMTP_USERNAME }}'"
        PGADMIN_CONFIG_MAIL_PASSWORD: "'{{ .PGADMIN_SMTP_PASSWORD }}'"
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: PGADMIN_DB_PASSWORD
    - secretKey: POSTGRES_USER
      remoteRef:
        key: PGADMIN_DB_USERNAME
    - secretKey: POSTGRES_DB
      remoteRef:
        key: PGADMIN_DB_DATABASE
    - secretKey: PGADMIN_DEFAULT_EMAIL
      remoteRef:
        key: PGADMIN_ADMIN_EMAIL
    - secretKey: PGADMIN_SETUP_EMAIL
      remoteRef:
        key: PGADMIN_ADMIN_EMAIL
    - secretKey: PGADMIN_DEFAULT_PASSWORD
      remoteRef:
        key: PGADMIN_ADMIN_PASSWORD
    - secretKey: PGADMIN_SETUP_PASSWORD
      remoteRef:
        key: PGADMIN_ADMIN_PASSWORD
    - secretKey: PGADMIN_SMTP_HOST
      remoteRef:
        key: PGADMIN_SMTP_HOST
    - secretKey: PGADMIN_SMTP_USERNAME
      remoteRef:
        key: PGADMIN_SMTP_USERNAME
    - secretKey: PGADMIN_SMTP_PASSWORD
      remoteRef:
        key: PGADMIN_SMTP_PASSWORD
