apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pgadmin-route
  namespace: pgadmin
  annotations:
    k8s-dns.nathanv.me/hostname: pgadmin.nathanv.app
    k8s-dns.nathanv.me/external: tunnel.nathanv.app
    k8s-dns.nathanv.me/internal: reverse-proxy.svc.nathanv.home
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`pgadmin.nathanv.app`)
      kind: Rule
      services:
        - name: pgadmin-service
          port: 80
  tls:
    certResolver: le
    domains:
      - sans:
          - "*.nathanv.app"
