apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: pgadmin-pvc-data
    namespace: pgadmin
spec:
    storageClassName: longhorn
    accessModes:
      - ReadWriteOnce
    resources:
        requests:
            storage: 100Mi
