apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-pvc-data
  namespace: pgadmin
spec:
  storageClassName: longhorn-rwx
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
