apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacamole-guacd-deployment
  namespace: guacamole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guacamole-guacd
  template:
    metadata:
      labels:
        app: guacamole-guacd
    spec:
      nodeSelector:
        role: apps
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: guacd
          # registry-proxy image-prefix
          image: cr.nathanv.app/docker.io/guacamole/guacd:1.6.0
          ports:
            - containerPort: 4822
