apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: guacamole-env-external
  namespace: guacamole
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: guacamole-env
  data:
    - secretKey: OPENID_CLIENT_ID
      remoteRef:
        key: GUACAMOLE_OIDC_CLIENT_ID
    - secretKey: POSTGRESQL_PASSWORD
      remoteRef:
        key: GUACAMOLE_DB_PASSWORD
    - secretKey: POSTGRESQL_USERNAME
      remoteRef:
        key: GUACAMOLE_DB_USERNAME
    - secretKey: POSTGRESQL_DATABASE
      remoteRef:
        key: GUACAMOLE_DB_DATABASE
