apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: guacd-network-policy
  namespace: guacamole
spec:
  podSelector:
    matchLabels:
      app: guacamole-guacd
  policyTypes:
    - Ingress
  # only permit ingress from guacamole frontend
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: guacamole
      ports:
        - protocol: TCP
          port: 4822
