apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: guacd-network-policy
  namespace: guacamole
spec:
  podSelector:
    matchLabels:
      app: guacamole-guacd
  policyTypes:
    - Ingress
    - Egress
  # only permit ingress from guacamole frontend
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: guacamole
      ports:
        - protocol: TCP
          port: 4822
  # allow egress for SSH-ing
  egress:
    - to:
        # restrict to local network
        - ipBlock:
            cidr: 10.0.0.1/20
      ports:
        - protocol: TCP
          port: 22
