apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: guacamole-pvc-initdb
  namespace: guacamole
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
