apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bitwarden-access-token
  namespace: external-secrets
spec:
  encryptedData:
    token: AgCjUaImtKsBeKpzyX41fIDF9DmqZC/7EMm7sRbhL8affHS2G2x5SbxyGo7MIoSrGv1eVfUKidECSB8gPhTCn9rTFYjPwuWMXE/KCD9hxbO6WGdzEVqem8IFmUc8dYwgY2aj6lXaK6vOJEUGHmfhRUDrLIdAO45cKPKBSul5VkIRmC8HPtLRT1CWvsa2N6rP+BgRBbwzKhviF/EA0vdRHO6DbYz43kS6mRRj40qgMHl0a8zrDb3vaUUgGoTGeC/Szy/y/LGG+hvQkcTPa53NYd4SFe1Qs/UaPjoUd5ba81JdpibHShTZIO071IiPgCwWuec6Le5WR5valVgUGRAGoq5ebKnQw4K4nWxLZwTbYobRlhgliZ/N3HNJ3YRpzb4k/6QxT0jLWfPQhqKGcO2YYsGP8Q+pV6Yuv2g94aJp/FkWJNdScv2BGVHI0LIu5Vfj/EGca/0UDdTa4Fb+ohGkYt/n0QWRVHsj62KT3zwZ6HtD3h3C2lIW37GoDuGA28T6phk+WvM7bAEzACt/8kE9x/PfTxj+/M6I0j7rE4YYGJSuin4UYyoVSOGJtRJBBw6hkeb/J33Zlr2vq/+gHF+SlB+I+d2TMOTbs5Yx1NsKRhDJ9Stzt/Yfmza79QzO7nxcan2AVdFvLmkIsslDi6MCptgv9egZk9JSBqCUJ8iwxbscIZvFttJKbyHeYA1VJMNoFlZzKpUMl6rZb8YdELwBhQhCasqQC8ZGK1iYZUBI1aqYO5aJLUXJjsGmYs4oFBTuoJsrWnL6tLfLqWXGz8GDr8rNsNR/Y9rq6cNpiSbLoCpJUSYt0TTd80ebay5rfb9y
  template:
    metadata:
      name: bitwarden-access-token
      namespace: external-secrets
