etcd-s3: true
etcd-s3-endpoint: s3.us-west-001.backblazeb2.com
etcd-s3-bucket: nathanv-private
etcd-s3-region: us-west-001
etcd-s3-access-key: {accesskey: ''}
etcd-s3-secret-key: {secretkey: ''}
etcd-s3-folder: etcd
kube-apiserver-arg:
  - oidc-issuer-url=https://authentik.nathanv.app/application/o/headlamp/
  - oidc-client-id={clientid}
  - oidc-username-claim=email
