apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: adsb-readsb-env-external
  namespace: adsb
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: adsb-readsb-env
  data:
    - secretKey: LAT
      remoteRef:
        key: ADSB_LAT
    - secretKey: LONG
      remoteRef:
        key: ADSB_LON
    - secretKey: ALT
      remoteRef:
        key: ADSB_ALT
