apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: adsb-piaware-env-external
  namespace: adsb
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: adsb-piaware-env
  data:
    - secretKey: FEEDER_ID
      remoteRef:
        key: ADSB_FLIGHTAWARE_FEEDER_ID
