apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: adsb-flightradar24-env
  namespace: adsb
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: adsb-flightradar24-env
  data:
    - secretKey: FR24KEY
      remoteRef:
        key: ADSB_FLIGHTRADAR24_KEY
