apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adsb-pvc-readsb-autogain
  namespace: adsb
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
