apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: servicemonitor-readsb
  namespace: adsb
spec:
  endpoints:
    - interval: 30s
      targetPort: 9273
      path: /metrics
  namespaceSelector:
    matchNames:
      - adsb
  selector:
    matchLabels:
      app: readsb-metrics
