apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maybe-pvc-postgresql
  namespace: maybe
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
