apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maybe-pvc-data
  namespace: maybe
spec:
  storageClassName: longhorn-rwx
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
