apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: headlamp-secrets-external
  namespace: headlamp
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: headlamp-secrets
  data:
    - secretKey: config.oidc.clientID
      remoteRef:
        key: HEADLAMP_OIDC_CLIENT_ID
    - secretKey: config.oidc.clientSecret
      remoteRef:
        key: HEADLAMP_OIDC_CLIENT_SECRET
