apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp-release
  namespace: headlamp
spec:
  releaseName: headlamp
  chart:
    spec:
      chart: headlamp
      sourceRef:
        kind: HelmRepository
        name: headlamp-repo
        namespace: headlamp
      version: "0.37.0"
  interval: 1h0m0s
  values:
    nodeSelector:
      role: apps
    clusterRoleBinding:
      create: true
    # https://github.com/headlamp-k8s/plugins/tree/main/flux
    pluginsManager:
      enabled: true
      # registry-proxy block-start
      baseImage: cr.nathanv.app/docker.io/node:lts-alpine
      # registry-proxy block-end
      configContent: |
        plugins:
          - name: headlamp_flux
            source: https://artifacthub.io/packages/headlamp/headlamp-plugins/headlamp_flux
            version: 0.5.0
    config:
      oidc:
        issuerURL: https://authentik.nathanv.app/application/o/headlamp/
        scopes: openid,profile,email
    # registry-proxy block-start
    image:
      registry: cr.nathanv.app/ghcr.io
    # registry-proxy block-end
    persistentVolumeClaim:
      enabled: true
      storageClassName: longhorn-rwx
      size: 100Mi
      accessModes:
        - ReadWriteMany
  valuesFrom:
    - kind: Secret
      name: headlamp-secrets
      valuesKey: config.oidc.clientID
      targetPath: config.oidc.clientID
    - kind: Secret
      name: headlamp-secrets
      valuesKey: config.oidc.clientSecret
      targetPath: config.oidc.clientSecret
