apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp-release
  namespace: headlamp
spec:
  releaseName: headlamp
  chart:
    spec:
      chart: headlamp
      sourceRef:
        kind: HelmRepository
        name: headlamp-repo
        namespace: headlamp
      version: "0.36.0"
  interval: 1h0m0s
  values:
    nodeSelector:
      role: apps
    clusterRoleBinding:
      create: false
    # https://github.com/headlamp-k8s/plugins/tree/main/flux
    config:
      pluginsDir: /build/plugins
      pluginsManager:
        enabled: true
        configContent: |
          plugins:
            - name: headlamp_flux
              source: https://artifacthub.io/packages/headlamp/headlamp-plugins/headlamp_flux
              version: 0.5.0
      oidc:
        issuerURL: https://authentik.nathanv.app/application/o/headlamp/
        scopes: openid,profile,email
    # registry-proxy block-start
    image:
      registry: cr.nathanv.app/ghcr.io
    # registry-proxy block-end
    persistentVolumeClaim:
      enabled: true
      storageClassName: longhorn-rwx
      size: 100Mi
      accessModes:
        - ReadWriteMany
    volumeMounts:
      - mountPath: /build/plugins
        name: headlamp-plugins
    volumes:
      - name: headlamp-plugins
        persistentVolumeClaim:
          claimName: headlamp
  valuesFrom:
    - kind: Secret
      name: headlamp-secrets
      valuesKey: config.oidc.clientID
      targetPath: config.oidc.clientID
    - kind: Secret
      name: headlamp-secrets
      valuesKey: config.oidc.clientSecret
      targetPath: config.oidc.clientSecret
