apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homebox-app-env-external
  namespace: homebox
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: homebox-app-env
  data:
    - secretKey: HBOX_AUTH_API_KEY_PEPPER
      remoteRef:
        key: HOMEBOX_SECRET_KEY
    - secretKey: HBOX_DATABASE_DATABASE
      remoteRef:
        key: HOMEBOX_DB_DATABASE
    - secretKey: HBOX_DATABASE_USERNAME
      remoteRef:
        key: HOMEBOX_DB_USERNAME
    - secretKey: HBOX_DATABASE_PASSWORD
      remoteRef:
        key: HOMEBOX_DB_PASSWORD
    - secretKey: HBOX_OIDC_CLIENT_ID
      remoteRef:
        key: HOMEBOX_OIDC_CLIENT_ID
    - secretKey: HBOX_OIDC_CLIENT_SECRET
      remoteRef:
        key: HOMEBOX_OIDC_CLIENT_SECRET
    - secretKey: HBOX_MAILER_HOST
      remoteRef:
        key: HOMEBOX_SMTP_HOST
    - secretKey: HBOX_MAILER_USERNAME
      remoteRef:
        key: HOMEBOX_SMTP_USERNAME
    - secretKey: HBOX_MAILER_PASSWORD
      remoteRef:
        key: HOMEBOX_SMTP_PASSWORD
