apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homebox-pvc-data
  namespace: homebox
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
