apiVersion: apps/v1
kind: Deployment
metadata:
  name: factorio-ddns-deployment
  namespace: factorio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: factorio-ddns
  template:
    metadata:
      labels:
        app: factorio-ddns
    spec:
      nodeSelector:
        role: apps
      containers:
        - env:
            - name: DOMAINS
              value: factorio.nathanv.app
            - name: PROXIED
              value: "false"
          envFrom:
            - secretRef:
                name: factorio-ddns-env
          image: cr.nathanv.app/docker.io/favonia/cloudflare-ddns:1.15.1
          name: factorio-ddns
