apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: factorio-deployment
  namespace: factorio
spec:
  replicas: 1
  serviceName: factorio
  selector:
    matchLabels:
      app: factorio
  template:
    metadata:
      labels:
        app: factorio
    spec:
      nodeSelector:
        role: apps
      initContainers:
        # https://www.jeffgeerling.com/blog/2019/mounting-kubernetes-secret-single-file-inside-pod
        - name: config-copy
          image: docker.io/library/busybox:1.37.0
          command: ['sh', '-c']
          args: ['mkdir -p /factorio/config && cp /config/server-settings.json /factorio/config/server-settings.json']
          volumeMounts:
            - mountPath: /factorio
              name: data-vol
            - mountPath: /config
              name: config-vol
      containers:
        - image: docker.io/factoriotools/factorio:stable-2.0.32
          name: factorio
          ports:
            - containerPort: 34197
              protocol: UDP
          volumeMounts:
            - mountPath: /factorio
              name: data-vol
      volumes:
        - name: data-vol
          persistentVolumeClaim:
            claimName: factorio-pvc
        - name: config-vol
          secret:
            secretName: factorio-config
