apiVersion: v1
kind: Service
metadata:
  name: factorio-service
  namespace: factorio
spec:
  type: LoadBalancer
  # use a static IP, since this is easier to maintain in Omada.
  loadBalancerIP: "10.0.1.5"
  selector:
    app: factorio
  ports:
    - port: 34197
      protocol: UDP
