apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: k8s-dns-env-external
  namespace: k8s-dns
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: k8s-dns-env
  data:
    - secretKey: CLOUDFLARE_API_TOKEN
      remoteRef:
        key: K8S_DNS_CLOUDFLARE_API_TOKEN
    - secretKey: TECHNITIUM_API_TOKEN
      remoteRef:
        key: K8S_DNS_TECHNITIUM_API_TOKEN
