apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: k8s-dns-kustomization
  namespace: k8s-dns
spec:
  interval: 1h0m0s
  path: ./crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-dns-repo
