#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: TODO
    username: ubuntu
    password: TODO
  ssh:
    install-server: true
    allow-pw: false
    authorized-keys:
      - TODO
  storage:
    layout:
      name: direct
  network:
    network:
      version: 2
      ethernets:
        all-en:
          match:
            name: en* # Matches all Ethernet interfaces
          dhcp4: true
  source: # use a minimal distribution
    id: ubuntu-server-minimal
  user-data:
    disable_root: true
  updates: all
  late-commands:
    - curtin in-target --target=/target systemctl enable ssh
