#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: TODO
    username: ubuntu
    password: TODO
  ssh:
    install-server: true
    allow-pw: false
    authorized-keys:
      - TODO
  storage:
    layout:
      name: direct
  network:
    # add extra network: key if does not work
    # https://canonical-subiquity.readthedocs-hosted.com/en/latest/reference/autoinstall-reference.html#network
    version: 2
    ethernets:
      all-en:
        match:
          name: en* # Matches all Ethernet interfaces
        dhcp4: true
        # Allow servers to use upstream DNS in the event
        # they need to pull the DNS server image
        # Prevents chicken and egg problem.
        # Use `resolvectl status` for debugging
        dhcp4-overrides:
          use-dns: false # disables netplan merging DHCP DNS
        nameservers:
          addresses: [10.0.1.4, 1.1.1.1]
    wifis:
      # match not allowed for WiFi. Hopefully this is consistent
      wlp2s0:
        dhcp4: true
        dhcp4-overrides:
          use-dns: false
        nameservers:
          addresses: [10.0.1.4, 1.1.1.1]
        access-points:
          TODO:
            password: TODO
  packages: []
  source: # use a minimal distribution
    id: ubuntu-server-minimal
  user-data:
    disable_root: true
  updates: all
  late-commands:
    - curtin in-target --target=/target systemctl enable ssh
