apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: webtrees-test-mysql-deployment
  namespace: webtrees-test
spec:
  replicas: 1
  serviceName: webtrees-test-mysql
  selector:
    matchLabels:
      app: webtrees-test-mysql
  template:
    metadata:
      labels:
        app: webtrees-test-mysql
    spec:
      nodeSelector:
        role: apps
      initContainers:
        - name: lost-found-fix
          image: docker.io/library/busybox:1.37.0
          command: ['sh', '-c']
          args: ['rm -rf /var/lib/mysql/lost+found']
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-vol
      containers:
        - env:
            - name: MARIADB_RANDOM_ROOT_PASSWORD
              value: "1"
            - name: MARIADB_USER
              value: webtrees
            - name: MARIADB_DATABASE
              value: webtrees
          envFrom:
            - secretRef:
                name: webtrees-test-env
          image: docker.io/library/mariadb:11.7.2
          name: mariadb
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-vol
      volumes:
        - name: mysql-vol
          persistentVolumeClaim:
            claimName: webtrees-test-pvc-mysql
