apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: webtrees-test-db-env-external
  namespace: webtrees-test
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: webtrees-test-db-env
  data:
    - secretKey: MARIADB_PASSWORD
      remoteRef:
        key: WEBTREES_TEST_DB_PASSWORD
    - secretKey: MARIADB_USER
      remoteRef:
        key: WEBTREES_TEST_DB_USERNAME
    - secretKey: MARIADB_DATABASE
      remoteRef:
        key: WEBTREES_TEST_DB_DATABASE
