apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webtrees-pvc-modules
  namespace: webtrees-test
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
