apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webtrees-test-pvc-data
  namespace: webtrees-test
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
