apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webtrees-test-env
  namespace: webtrees-test
spec:
  encryptedData:
    DB_PASS: AgAiVMx67GucaAkeExgHxI+YaAMrVvDcNVmUTdk8Ol6iJZktIjMrxbsHNzE32OE+mcSNIpCB2dgIhghEMaL7Lr7DDuNQdmrjTuxFbdDTYf8SrEo2Ch49dAZ3wXO8rjYjGDFhfC7qx+qvYXR93Sjjb9MqPP8I75bYKwa5GGcbMQNGL4Hx77upIRxTcinMQLUy+PXNync+5GkQHCd4PAZBWHNzra5/oXVFAR8h2xT3RVermdhVLh9HtQqfaWiQ5cG692JoeP2U5a1+pgi5RpqfWCm5IzxzodrJWygy2CzRKehco7jkXCkk4j3OzSjkg8ULqV3yIEAWRUmD5XSDB+WTwJz5eaiZVdWMjA8okBXd/IOkcFuNG1xEgZAl/R7v5mj/lV42R0hrZgI9LoNydo1uw+tEyrj7fJX4l9CdcdK9GL+4jMG4A2vyvDJY+5Vt73Cm9hX0acVlUHgyT0V5wkv0vNVsAlaOzDKrPXug/LqesrCJynnDWqIp7S6ZlcUF7pgcOJTcKcF/W28XvLfwdRK2WrzOe/0wYaQD7tj04LrIhLY+KjVlntK2IVsAXAH7PPTaWeLrHD8MzrYiB5T4mqO4hEs1b+Ygv4TqN7y0dmq+enhqPkGZFTN9Ish2hLYQaF4meRdPxqKVo+OjF6hf3HVaxL9TSv7UIDDcJYJcrpU7vcXgj209bc173dacYvUlQoEc9DjfYGZKbinH8vfTcqUv80ak8HAaxmDO82ujk9t1ljA=
    MARIADB_PASSWORD: AgABtcYwvGvrhL4TENh3EeIoNtpnEG+obkXZuZGeL/zwF3iHjpUWEcAFr1sBSOEFIw2EsaVL992k/MsHFMEKYtoOiIJNjAqpi0QsbkwoDiPY4s5Mk3f2D9c7kb6i4z86DEiWDQrGtU8b5lo0Cj6XAkZ+DnhCd2byICIQ0eXziAeiS1EWRPf7K4nbfU5U+8wWJcz8QlsCJdwepnjU8WH/WHboSw0JuMganlQX24OG8q50BuQe1e+ekvG1pclMpPPZ7Cq3/NQcKeAaPj6q+Phm5z3aAXlAPX8VK82zO7fXIAat6Zi+EYj00j0oTrHs2+PFaVzfmaPsI1xQoRGv2gHG3ui56mar/HM98ww1fS+7P3UWbO4X3+hAnHkkANNw6JTM0nb5ViDCCc+mR7txdh1fVrPUxVPrIHkMhQXP4L9KQKp+w6utdN/cIiUjOmvq6qq/xe/k7gkbMcNTotykUk/40ymYlJoa7O05Ahr9x2m9I27JMax6y4RhbEY34ig4FjyPo71uzf6tbTfR2OEVPmMlGemEXEX2eyVuH0GIjWOHDnGIkU7rQGBpvX3XObiF2f4ca2HeqaoPXbbLOQz1Oa8AJqq2wfaiNQCTEzcejNZAzkTtDwNwK6mr3fWeM56p/vJk4Zg2mc2ERyED8DhxFgUwYEGcj8gkAqsGxXhUhXltpZDOJkis72ySGIYREUp/FArVAEbvB30ene0vQnSTt6QF2u7v+wnDU+86Jpr7L2ST8Lk=
  template:
    metadata:
      creationTimestamp: null
      name: webtrees-test-env
      namespace: webtrees-test
