apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-secrets-external
  namespace: grafana
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: grafana-secrets
  data:
    - secretKey: adminUser
      remoteRef:
        key: GRAFANA_ADMIN_USER
    - secretKey: adminPassword
      remoteRef:
        key: GRAFANA_ADMIN_PASSWORD
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: GRAFANA_DB_PASSWORD
    - secretKey: grafana_ini.database.password
      remoteRef:
        key: GRAFANA_DB_PASSWORD
    - secretKey: POSTGRES_USER
      remoteRef:
        key: GRAFANA_DB_USERNAME
    - secretKey: grafana_ini.database.user
      remoteRef:
        key: GRAFANA_DB_USERNAME
    - secretKey: POSTGRES_DB
      remoteRef:
        key: GRAFANA_DB_DATABASE
    - secretKey: grafana_ini.database.name
      remoteRef:
        key: GRAFANA_DB_DATABASE
    - secretKey: grafana_ini.auth_generic_oauth.client_id
      remoteRef:
        key: GRAFANA_OIDC_CLIENT_ID
    - secretKey: grafana_ini.auth_generic_oauth.client_secret
      remoteRef:
        key: GRAFANA_OIDC_CLIENT_SECRET
    - secretKey: grafana_ini.smtp.host
      remoteRef:
        key: GRAFANA_SMTP_HOST
    - secretKey: grafana_ini.smtp.user
      remoteRef:
        key: GRAFANA_SMTP_USERNAME
    - secretKey: grafana_ini.smtp.password
      remoteRef:
        key: GRAFANA_SMTP_PASSWORD
