apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-route
  namespace: grafana
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`grafana.nathanv.app`)
      kind: Rule
      services:
        - name: grafana
          port: 80
  tls:
    certResolver: le
    domains:
      - sans:
          - "*.nathanv.app"
