apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc-postgresql
  namespace: grafana
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
