apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-release
  namespace: grafana
spec:
  releaseName: grafana
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: grafana-repo
        namespace: grafana
      version: "8.8.4"
  interval: 1h0m0s
  values:
    persistence:
      enabled: true
      type: pvc
      size: 1Gi
      storageClassName: longhorn
