apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-release
  namespace: grafana
spec:
  releaseName: grafana
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: grafana-repo
        namespace: grafana
      version: "9.4.3"
  interval: 1h0m0s
  values:
    # registry-proxy block-start
    global:
      imageRegistry: cr.nathanv.app/docker.io
    # registry-proxy block-end
    persistence:
      enabled: true
      type: pvc
      size: 200Mi
      storageClassName: longhorn-rwx
      accessModes:
        - ReadWriteMany
    # adminUser:
    # adminPassword:
    grafana.ini:
      server:
        root_url: https://grafana.nathanv.app
      auth.generic_oauth:
        enabled: true
        allow_sign_up: true
        # this will need to be false on first-time setup
        # Log in with Authentik user, log out, log in as admin,
        # Make authentik user an admin, disable builtin admin account, log out
        auto_login: true
        name: Authentik
        client_id: $__file{/etc/secrets/grafana_secrets/grafana_ini.auth_generic_oauth.client_id}
        client_secret: $__file{/etc/secrets/grafana_secrets/grafana_ini.auth_generic_oauth.client_secret}
        scopes: "openid profile email"
        auth_url: https://authentik.nathanv.app/application/o/authorize/
        token_url: https://authentik.nathanv.app/application/o/token/
        api_url: https://authentik.nathanv.app/application/o/userinfo/
        signout_redirect_url: https://authentik.nathanv.app/application/o/grafana/end-session/
        login_attribute_path: preferred_username
        # manage roles manually
        skip_org_role_sync: true
      smtp:
        enabled: true
        host: $__file{/etc/secrets/grafana_secrets/grafana_ini.smtp.host}
        user: $__file{/etc/secrets/grafana_secrets/grafana_ini.smtp.user}
        password: $__file{/etc/secrets/grafana_secrets/grafana_ini.smtp.password}
        from_address: grafana@nvaughn.email
        from_name: Grafana
        skip_verify: false
        startTLS_policy: MandatoryStartTLS
      database:
        type: postgres
        host: grafana-postgresql-service.grafana.svc.cluster.local:5432
        name: grafana
        user: grafana
        password: $__file{/etc/secrets/grafana_secrets/grafana_ini.database.password}
      # https://grafana.com/docs/grafana/latest/observability-as-code/provision-resources/git-sync-setup/#enable-required-feature-toggles
      feature_toggles:
        provisioning: true
        kubernetesDashboards: true
    extraSecretMounts:
      - name: grafana-secrets-mount
        secretName: grafana-secrets
        defaultMode: 440
        mountPath: /etc/secrets/grafana_secrets
        readOnly: true
  valuesFrom:
    - kind: Secret
      name: grafana-secrets
      valuesKey: adminUser
      targetPath: adminUser
    - kind: Secret
      name: grafana-secrets
      valuesKey: adminPassword
      targetPath: adminPassword
  # grafana does not allow setting the value of secrets in grafana.ini directly in values.yaml
