apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: portainer-route
  namespace: portainer
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`portainer.nathanv.app`)
      kind: Rule
      services:
        - name: portainer
          port: 9000
  tls:
    certResolver: le
    domains:
      - sans:
          - "*.nathanv.app"
