apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: portainer-release
  namespace: portainer
spec:
  releaseName: portainer
  chart:
    spec:
      chart: portainer
      sourceRef:
        kind: HelmRepository
        name: portainer-repo
        namespace: portainer
      version: "2.33.5"
  interval: 1h0m0s
  values:
    # registry-proxy block-start
    image:
      repository: cr.nathanv.app/docker.io/portainer/portainer-ce
    # registry-proxy block-end
    nodeSelector:
      role: apps
    persistence:
      enabled: true
      # ideally this would be a stateful set since
      # portainer also has an embedded database, but helm chart does not allow that
      storageClass: longhorn-rwx
      accessMode: ReadWriteMany
      size: 200Mi
