apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: portainer-release
  namespace: portainer
spec:
  releaseName: portainer
  chart:
    spec:
      chart: portainer
      sourceRef:
        kind: HelmRepository
        name: portainer-repo
        namespace: portainer
      version: "1.0.58"
  interval: 1h0m0s
  values:
    nodeSelector:
      role: apps
    persistence:
      enabled: true