apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-route
  namespace: longhorn

spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`longhorn.nathanv.app`)
    kind: Rule
    services:
    - name: longhorn-frontend
      port: 80
  tls:
    certResolver: le
    domains:
    - sans:
      - "*.nathanv.app"
