apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn-release
  namespace: longhorn
spec:
  releaseName: longhorn
  chart:
    spec:
      chart: longhorn
      sourceRef:
        kind: HelmRepository
        name: longhorn-repo
        namespace: longhorn
      version: "1.8.0"
  interval: 1h0m0s
  values:
    persistence:
      defaultClassReplicaCount: 3
      # tries to keep a replica on the node the volume is attached to
      defaultDataLocality: best-effort
      # prevents data from being deleted when pvc is deleted
      reclaimPolicy: Retain
    defaultSettings:
      backupTarget: s3://nathanv-private@us-west-001/longhorn
      backupTargetCredentialSecret: longhorn-env
    # just limit the 1-off components to the apps nodes
    # longhorn manager needs to run on all nodes
    longhornUI:
      nodeSelector:
        role: apps
    longhornDriver:
      nodeSelector:
        role: apps
    metrics:
      serviceMonitor:
        enabled: true
