apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn-release
  namespace: longhorn
spec:
  releaseName: longhorn
  chart:
    spec:
      chart: longhorn
      sourceRef:
        kind: HelmRepository
        name: longhorn-repo
        namespace: longhorn
      version: 1.6.0
  interval: 1h0m0s
  values:
    defaultSettings:
      defaultReplicaCount: 3
