apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn-release
  namespace: longhorn
spec:
  releaseName: longhorn
  chart:
    spec:
      chart: longhorn
      sourceRef:
        kind: HelmRepository
        name: longhorn-repo
        namespace: longhorn
      version: "1.7.2"
  interval: 1h0m0s
  values:
    persistence:
      defaultClassReplicaCount: 3
    defaultSettings:
      backupTarget: s3://nathanv-private@us-west-001/longhorn
      backupTargetCredentialSecret: longhorn-env
