apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: snippet-box-pvc
    namespace: snippet-box
spec:
    storageClassName: longhorn
    accessModes:
      - ReadWriteOnce
    resources:
        requests:
            storage: 100Mi
