apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: snippet-box-pvc
  namespace: snippet-box
spec:
  storageClassName: longhorn-rwx
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
