apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: snippet-box-pvc
  namespace: snippet-box
spec:
  # snippet box has an embedded sqlite database that doesn't like to share
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
