apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: system-upgrade-kustomization
    namespace: system-upgrade
spec:
    interval: 1h0m0s
    path: ./
    prune: true
    sourceRef:
        kind: GitRepository
        name: system-upgrade-repo
