apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: system-upgrade-repo
  namespace: system-upgrade
spec:
  interval: 1h0m0s
  url: https://github.com/rancher/system-upgrade-controller/
  ref:
    tag: v0.14.2
