apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  namespace: sealed-secrets
resources:
  - release.yaml
configMapGenerator:
  - name: sealed-secrets-values
    files:
      - values.yaml=values.yaml
