apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets-release
  namespace: sealed-secrets
spec:
  chart:
    spec:
      chart: sealed-secrets
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets-repo
        namespace: sealed-secrets
      version: "2.18.0"
  install:
    crds: Create
  interval: 1h0m0s
  releaseName: sealed-secrets-controller
  targetNamespace: sealed-secrets
  upgrade:
    crds: CreateReplace
  values:
    # registry-proxy block-start
    image:
      registry: cr.nathanv.app/docker.io
    # registry-proxy block-end
    metrics:
      serviceMonitor:
        enabled: true
    nodeSelector:
      role: apps
