apiVersion: nathanv.me/v1
kind: DNSConfig
metadata:
  name: node5-dns-config
  namespace: devices
spec:
  hostname: will.nathanv.home
  internalIP: "10.0.0.24"
  comments: Kubernetes node 5, E8-6A-64-76-3B-05
