apiVersion: nathanv.me/v1
kind: DNSConfig
metadata:
  name: node1-dns-config
  namespace: devices
spec:
  hostname: billy.nathanv.home
  internalIP: "10.0.0.20"
  comments: Kubernetes node 1, E8-6A-64-78-E1-63
