{
 "title": "Readsb-protobuf",
 "description": "Used to visualise metrics collected from the mikenye/readsb-protobuf docker image.\r\n\r\nCurrently without the polar range and tracked aircraft sections. Also missing MLAT metrics from the prometheus exporter for the time being",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Currrently Tracked Aircraft",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "readsb_cpr_local_aircraft_relative",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "readsb",
     "query": "SELECT last(\"Lat\") FROM \"aircraft\" WHERE (\"host\" = 'readsb' AND \"Icao\" != '') AND time >= now() - 1m GROUP BY \"Icao\"",
     "select": [
      [
       { "params": [ "tracks_with_position" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Maximum Range",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "readsb_max_distance_in_metres",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "miles",
     "measurement": "readsb",
     "select": [
      [
       { "params": [ "max_distance_in_metres" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Avg. SNR",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "readsb_local_signal-readsb_local_noise",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "readsb",
     "select": [
      [
       { "params": [ "local_signal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "signal" ], "type": "alias" }
      ],
      [
       { "params": [ "local_noise" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "noise" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "% Strong Signals",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "readsb_local_strong_signals/readsb_local_accepted",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "readsb",
     "select": [
      [
       { "params": [ "local_accepted" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "local_accepted" ], "type": "alias" }
      ],
      [
       { "params": [ "local_strong_signals" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "local_strong_signals" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  { "title": "Performance Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Message Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Messages Received",
     "expr": "readsb_messages",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "Messages Received",
     "measurement": "readsb",
     "select": [
      [
       { "params": [ "messages" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "Messages > 3dbFS",
     "expr": "readsb_local_strong_signals",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "Messages > 3dbFS",
     "measurement": "readsb",
     "select": [
      [
       { "params": [ "local_strong_signals" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "Positions/s (RHS)",
     "expr": "readsb_cpr_global_ok",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "Position/s (RHS)",
     "measurement": "readsb",
     "select": [
      [
       { "params": [ "cpr_global_ok" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "/60" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Positions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "ADS-B",
     "expr": "readsb_tracks_with_position",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "ADS-B",
     "measurement": "readsb",
     "select": [
      [
       { "params": [ "tracks_with_position" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "readsb CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "SDR Reader",
     "expr": "readsb_cpu_reader/60000",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "SDR Reader",
     "measurement": "readsb",
     "select": [
      [
       { "params": [ "cpu_reader" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "/60000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "Demodulator",
     "expr": "readsb_cpu_demod/60000",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "Demodulator",
     "measurement": "readsb",
     "select": [
      [
       { "params": [ "cpu_demod" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "/60000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "Background",
     "expr": "readsb_cpu_background/60000",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "Background",
     "measurement": "readsb",
     "select": [
      [
       { "params": [ "cpu_background" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "/60000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Tracks Seen",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Tracks",
     "expr": "readsb_tracks_with_position",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "Tracks",
     "measurement": "readsb",
     "select": [
      [
       { "params": [ "tracks_with_position" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "Tracks with single message",
     "expr": "readsb_tracks_single_message",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "Tracks with single message",
     "measurement": "readsb",
     "select": [
      [
       { "params": [ "tracks_single_message" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  { "title": "Autogain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Autogain: Gain Levels",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "expr": "autogain_autogain_current_value",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Current Gain",
     "measurement": "autogain",
     "select": [
      [
       { "params": [ "autogain_current_value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "current" ], "type": "alias" }
      ],
      [
       { "params": [ "autogain_max_value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "max" ], "type": "alias" }
      ],
      [
       { "params": [ "autogain_min_value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "min" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    { "expr": "autogain_autogain_max_value", "legendFormat": "Maximum Gain" },
    { "expr": "autogain_autogain_min_value", "legendFormat": "Minimum Gain" }
   ]
  },
  {
   "title": "Signal Strength",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "expr": "readsb_local_signal",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "Signal",
     "measurement": "readsb",
     "select": [
      [
       { "params": [ "local_signal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Signal" ], "type": "alias" }
      ],
      [
       { "params": [ "local_noise" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Noise" ], "type": "alias" }
      ],
      [
       { "params": [ "local_peak_signal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Peak Signal" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    { "expr": "readsb_local_noise", "legendFormat": "Noise" },
    { "expr": "readsb_local_peak_signal", "legendFormat": "Peak Signal" }
   ]
  }
 ]
}