apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-configmap
  namespace: cloudflared
data:
  config.yaml: |-
    tunnel: k8s-tunnel
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
    - hostname: readsb.nathanv.app
      service: https://traefik.traefik.svc.cluster.local:443
      originRequest:
        noTLSVerify: true
        originServerName: "*traefik*"
    - hostname: authentik.nathanv.app
      service: https://traefik.traefik.svc.cluster.local:443
      originRequest:
        noTLSVerify: true
        originServerName: "*traefik*"
    - hostname: bookstack.nathanv.app
      service: https://traefik.traefik.svc.cluster.local:443
      originRequest:
        noTLSVerify: true
        originServerName: "*traefik*"
    - hostname: christmas.nathanv.app
      service: https://traefik.traefik.svc.cluster.local:443
      originRequest:
        noTLSVerify: true
        originServerName: "*traefik*"
    - hostname: grafana.nathanv.app
      service: https://traefik.traefik.svc.cluster.local:443
      originRequest:
        noTLSVerify: true
        originServerName: "*traefik*"
    - hostname: guacamole.nathanv.app
      service: https://traefik.traefik.svc.cluster.local:443
      originRequest:
        noTLSVerify: true
        originServerName: "*traefik*"
    - hostname: cr.nathanv.app
      service: https://traefik.traefik.svc.cluster.local:443
      originRequest:
        noTLSVerify: true
        originServerName: "*traefik*"
    - hostname: kubetail.nathanv.app
      service: https://traefik.traefik.svc.cluster.local:443
      originRequest:
        noTLSVerify: true
        originServerName: "*traefik*"
    - hostname: longhorn.nathanv.app
      service: https://traefik.traefik.svc.cluster.local:443
      originRequest:
        noTLSVerify: true
        originServerName: "*traefik*"
    - hostname: lubelogger.nathanv.app
      service: https://traefik.traefik.svc.cluster.local:443
      originRequest:
        noTLSVerify: true
        originServerName: "*traefik*"
    - hostname: pgadmin.nathanv.app
      service: https://traefik.traefik.svc.cluster.local:443
      originRequest:
        noTLSVerify: true
        originServerName: "*traefik*"
    - hostname: phpmyadmin.nathanv.app
      service: https://traefik.traefik.svc.cluster.local:443
      originRequest:
        noTLSVerify: true
        originServerName: "*traefik*"
    - hostname: prometheus.nathanv.app
      service: https://traefik.traefik.svc.cluster.local:443
      originRequest:
        noTLSVerify: true
        originServerName: "*traefik*"
    - hostname: scrutiny.nathanv.app
      service: https://traefik.traefik.svc.cluster.local:443
      originRequest:
        noTLSVerify: true
        originServerName: "*traefik*"
    - hostname: snippet-box.nathanv.app
      service: https://traefik.traefik.svc.cluster.local:443
      originRequest:
        noTLSVerify: true
        originServerName: "*traefik*"
    - hostname: stirling-pdf.nathanv.app
      service: https://traefik.traefik.svc.cluster.local:443
      originRequest:
        noTLSVerify: true
        originServerName: "*traefik*"
    - hostname: technitium-dns.nathanv.app
      service: https://traefik.traefik.svc.cluster.local:443
      originRequest:
        noTLSVerify: true
        originServerName: "*traefik*"
    - hostname: webtrees.nathanv.app
      service: https://traefik.traefik.svc.cluster.local:443
      originRequest:
        noTLSVerify: true
        originServerName: "*traefik*"
    - service: http_status:404
