apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tunnel-credentials
  namespace: cloudflared
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: tunnel-credentials
  data:
    - secretKey: credentials.json
      remoteRef:
        key: CLOUDFLARED_CREDENTIALS_FILE
