apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgBdnB4ww2HZs/FHfij536hvo5G/J/8dHlo6jTJRUASkeGyv8DjaKROrB0HRQNkskf82RPTa5pFMvbRcsg3Wh2kwsWWz/2wSFJV9r8/iAH/n837BQMejmsbLt4LLHJNdfadpYVJToG5i+CwuWyAlhjpOKuRXTOJoGvbytD7De7VYrl3Op8XKFOjI8bp1rFCw5ep4icKvyH/SG8YPUEadcgWuGiGwvGQjzu32TNOmfpuk967SR5D3H/ijOkfEjhjjNZpC+szRW8SYCBCzAcP9Fvtb7K8guafqRkddzJtPgtD5kyWe7naAx3Q0O4AKmZ9PytVy3gA9nXUDKw001X7SsbNm2nyQ83Dr7tM8SuKBqmWRZNHyybJ9L/FT/pAA+pMoG6nO4XsO8rWKEeK6VVzW3YgcOsiorcc71dR0ZNBDkwgfCvSWg9QtKW0im7/2MFW0lGUCgyC5O5QggNGwft5LKRHQOFLjwYuSHuyVH7n//Rd4fhBmER+brLq4cJKpUxI+rgnC6UXOV9sQEk/CTHAerw3ibZwwoYvsDZKH3SSN03P8R7hsckUS4QTprJMca7rnfgx+F8jAiDaMtUHNxLTv+pePbuXrfpdRvrgk1jWCHbld76Pln3xKqXKDpK3zRahn9V9gnLEtqqV9qV9Y5nbCsqiMQXsoXbU6uCB/QyfMZxgWy4JCKPi1PJO0EHdaRWqIikxwW+Ac4RotvwoRnHrNiplL0nCivfGEBHo/EPJcRR34CvVMXCWZcgdvm9RFYgsujDp8EpOs8FXs1vZv6HoOzDU1D/MeP9IA4tuEs15wPiCP9LLE9FcVVLT3T8ioYqKCnJMAQiD35VZYlPUJw9iZ9db/6Z3VaTi4oppXs+VvXS5v1P1+lfFk7Mm9iVn/gDFO7Yy180D+MJP/VvuRBbZldNOAHYtAZHsHPlZQJklX+djBQDmJCZM=
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflared
