apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mypypi-app-env
  namespace: mypypi
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: mypypi-app-env
    template:
      mergePolicy: Merge
      data:
        MYPYPI_DATABASE__URL: "postgresql://{{ .POSTGRES_USER }}:{{ .POSTGRES_PASSWORD }}@mypypi-postgresql-service.mypypi.svc.cluster.local/{{ .POSTGRES_DB }}"
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: MYPYPI_DB_PASSWORD
    - secretKey: POSTGRES_USER
      remoteRef:
        key: MYPYPI_DB_USERNAME
    - secretKey: POSTGRES_DB
      remoteRef:
        key: MYPYPI_DB_DATABASE
    - secretKey: MYPYPI_STORAGE__S3__ENDPOINT_URL
      remoteRef:
        key: MYPYPI_S3_ENDPOINT
    - secretKey: MYPYPI_STORAGE__S3__BUCKET_NAME
      remoteRef:
        key: MYPYPI_S3_BUCKET
    - secretKey: MYPYPI_STORAGE__S3__REGION_NAME
      remoteRef:
        key: MYPYPI_S3_REGION
    - secretKey: MYPYPI_STORAGE__S3__ACCESS_KEY_ID
      remoteRef:
        key: MYPYPI_S3_ACCESS_KEY_ID
    - secretKey: MYPYPI_STORAGE__S3__SECRET_ACCESS_KEY
      remoteRef:
        key: MYPYPI_S3_SECRET_ACCESS_KEY
