apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypypi-pvc-redis
  namespace: mypypi
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
