apiVersion: v1
kind: Service
metadata:
  name: mypypi-postgresql-service
  namespace: mypypi
spec:
  type: ClusterIP
  selector:
    app: mypypi-postgresql
  ports:
    - port: 5432
      protocol: TCP
