apiVersion: apps/v1
kind: Deployment
metadata:
    name: ntp-deployment
    namespace: ntp
spec:
    replicas: 1
    selector:
        matchLabels:
            app: ntp
    template:
        metadata:
            labels:
                app: ntp
        spec:
            nodeSelector:
                role: apps
            containers:
              - env:
                  - name: NTP_SERVERS
                    value: time.cloudflare.com
                image: docker.io/cturra/ntp:latest
                name: ntp
                ports:
                  - containerPort: 123
                    protocol: UDP
