apiVersion: v1
kind: Service
metadata:
    name: ntp-service
    namespace: ntp
    annotations:
        metallb.universe.tf/loadBalancerIPs: "10.0.1.3"
spec:
    type: LoadBalancer
    selector:
        app: ntp
    ports:
      - port: 123
        protocol: UDP
