apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki-release
  namespace: loki
spec:
  releaseName: loki
  chart:
    spec:
      chart: loki
      sourceRef:
        kind: HelmRepository
        name: loki-repo
        namespace: loki
      version: "6.45.2"
  interval: 1h0m0s
  values:
    # registry-proxy block-start
    sidecar:
      image:
        repository: cr.nathanv.app/docker.io/kiwigrid/k8s-sidecar
    memcached:
      image:
        repository: cr.nathanv.app/docker.io/library/memcached
    memcachedExporter:
      image:
        repository: cr.nathanv.app/docker.io/prom/memcached-exporter
    # registry-proxy block-end
    loki:
      # registry-proxy block-start
      image:
        registry: cr.nathanv.app/docker.io
      # registry-proxy block-end
      storage:
        type: filesystem
      auth_enabled: false
      # https://grafana.com/docs/loki/latest/setup/install/helm/install-monolithic/
      commonConfig:
        replication_factor: 1
      schemaConfig:
        configs:
          - from: "2024-04-01"
            store: tsdb
            object_store: filesystem
            schema: v13
            index:
              prefix: loki_index_
              period: 24h
      pattern_ingester:
        enabled: true
      limits_config:
        allow_structured_metadata: true
        volume_enabled: true
      ruler:
        enable_api: true
    minio:
      enabled: false
    deploymentMode: SingleBinary
    singleBinary:
      replicas: 1
      nodeSelector:
        role: apps
    chunksCache:
      nodeSelector:
        role: apps
    resultsCache:
      nodeSelector:
        role: apps
    gateway:
      nodeSelector:
        role: apps
      # registry-proxy block-start
      image:
        registry: cr.nathanv.app/docker.io
        # registry-proxy block-end
    # Zero out replica counts of other deployment modes
    backend:
      replicas: 0
    read:
      replicas: 0
    write:
      replicas: 0
    ingester:
      replicas: 0
    querier:
      replicas: 0
    queryFrontend:
      replicas: 0
    queryScheduler:
      replicas: 0
    distributor:
      replicas: 0
    compactor:
      replicas: 0
    indexGateway:
      replicas: 0
    bloomCompactor:
      replicas: 0
    bloomGateway:
      replicas: 0
    # disable testing
    test:
      enabled: false
    lokiCanary:
      enabled: false
