apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: netdata-route
  namespace: netdata
  annotations:
    k8s-dns.nathanv.me/hostname: netdata.nathanv.app
    k8s-dns.nathanv.me/external: tunnel.nathanv.app
    k8s-dns.nathanv.me/internal: reverse-proxy.svc.nathanv.home
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`netdata.nathanv.app`)
    kind: Rule
    services:
    - name: netdata
      port: 19999
  tls:
    certResolver: le
    domains:
    - sans:
      - "*.nathanv.app"
