apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: netdata-route
  namespace: netdata

spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`netdata.nathanv.app`)
    kind: Rule
    services:
    - name: netdata
      port: 19999
  tls:
    certResolver: le
    domains:
    - sans:
      - "*.nathanv.app"
