apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: netdata-release
  namespace: netdata
spec:
  chart:
    spec:
      chart: netdata
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: netdata-repo
        namespace: netdata
      version: "3.7.113"
  interval: 1h0m0s
  values:
    image:
      tag: "v2.0.3"
    parent:
      enabled: true
      claiming:
        enabled: false
    child:
      enabled: true