apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: rancher-route
  namespace: rancher
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`rancher.nathanv.app`)
      kind: Rule
      services:
        - name: rancher
          port: 80
  tls:
    certResolver: le
    domains:
      - sans:
          - "*.nathanv.app"
