apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: metallb-release
    namespace: metallb
spec:
    releaseName: metallb
    chart:
        spec:
            chart: metallb
            sourceRef:
                kind: HelmRepository
                name: metallb-repo
                namespace: metallb
            version: "0.14.8"
    interval: 1h0m0s
    values:
        speaker:
            nodeSelector:
                role: apps
        controller:
            nodeSelector:
                role: apps
