apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: freshrss-app-env-external
  namespace: freshrss
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: freshrss-app-env
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: FRESHRSS_DB_PASSWORD
    - secretKey: DB_USER
      remoteRef:
        key: FRESHRSS_DB_USERNAME
    - secretKey: DB_BASE
      remoteRef:
        key: FRESHRSS_DB_DATABASE
    - secretKey: OIDC_CLIENT_ID
      remoteRef:
        key: FRESHRSS_OIDC_CLIENT_ID
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: FRESHRSS_OIDC_CLIENT_SECRET
