apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freshrss-pvc-postgresql
  namespace: freshrss
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
