apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freshrss-pvc-data
  namespace: freshrss
spec:
  storageClassName: longhorn-rwx
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
