apiVersion: apps/v1
kind: Deployment
metadata:
  name: chrony-deployment
  namespace: chrony
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chrony
  template:
    metadata:
      labels:
        app: chrony
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              # when possible, run on the network controller
              matchExpressions:
              - key: role
                operator: In
                values:
                - network
      containers:
      - env:
        - name: NTP_SERVERS
          value: time.cloudflare.com
        - name: ENABLE_NTS
          value: "true"
        image: ghcr.io/dockur/chrony:4.6.1
        name: chrony
        ports:
        - containerPort: 123
          protocol: UDP
