apiVersion: v1
kind: Service
metadata:
  name: chrony-service
  namespace: chrony
spec:
  type: LoadBalancer
  loadBalancerIP: "10.0.1.3"
  selector:
    app: chrony
  ports:
    - port: 123
      protocol: UDP
