apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: actual-deployment
  namespace: actual
spec:
  replicas: 1
  serviceName: actual
  selector:
    matchLabels:
      app: actual
  template:
    metadata:
      labels:
        app: actual
    spec:
      nodeSelector:
        role: apps
      containers:
        # give up on OIDC for now, it still allows password login
        # which kind of defeats the purpose.
        # env:
        #   - name: ACTUAL_LOGIN_METHOD
        #     value: openid
        #   - name: ACTUAL_ALLOWED_LOGIN_METHODS
        #     value: openid
        #   - name: ACTUAL_OPENID_DISCOVERY_URL
        #     value: https://authentik.nathanv.app/application/o/actual/
        #   - name: ACTUAL_OPENID_SERVER_HOSTNAME
        #     value: actual.nathanv.app
        - image: ghcr.io/actualbudget/actual-server:25.3.0
          name: actual
          ports:
            - containerPort: 5006
          volumeMounts:
            - mountPath: /data
              name: actual-vol
      volumes:
        - name: actual-vol
          persistentVolumeClaim:
            claimName: actual-pvc
