apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actual-pvc
  namespace: actual
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
