apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: webtrees-app-env
  namespace: webtrees
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: webtrees-app-env
  data:
    - secretKey: DB_PASS
      remoteRef:
        key: WEBTREES_DB_PASSWORD
    - secretKey: DB_USER
      remoteRef:
        key: WEBTREES_DB_USERNAME
    - secretKey: DB_NAME
      remoteRef:
        key: WEBTREES_DB_DATABASE
