apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: webtrees-route
  namespace: webtrees
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`webtrees.nathanv.app`)
      kind: Rule
      services:
        - name: webtrees-service
          port: 80
  tls:
    certResolver: le
    domains:
      - sans:
          - "*.nathanv.app"
