apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: webtrees-pvc-mysql
    namespace: webtrees
spec:
    storageClassName: longhorn
    accessModes:
      - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
