apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webtrees-pvc-data
  namespace: webtrees
spec:
  storageClassName: longhorn-rwx
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
