apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secrets
  namespace: authentik
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: authentik-secrets
  data:
    - secretKey: authentik.email.host
      remoteRef:
        key: AUTHENTIK_SMTP_HOST
    - secretKey: authentik.email.username
      remoteRef:
        key: AUTHENTIK_SMTP_USERNAME
    - secretKey: authentik.email.password
      remoteRef:
        key: AUTHENTIK_SMTP_PASSWORD
    - secretKey: authentik.postgresql.password
      remoteRef:
        key: AUTHENTIK_DB_PASSWORD
    - secretKey: postgresql.auth.password
      remoteRef:
        key: AUTHENTIK_DB_PASSWORD
    - secretKey: postgresql.auth.username
      remoteRef:
        key: AUTHENTIK_DB_USERNAME
    - secretKey: postgresql.auth.database
      remoteRef:
        key: AUTHENTIK_DB_DATABASE
    - secretKey: authentik.secret_key
      remoteRef:
        key: AUTHENTIK_SECRET_KEY
