apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-pvc-media
  namespace: authentik
spec:
  storageClassName: longhorn-rwx
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi
