apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-pvc-media
  namespace: authentik
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
