apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik-release
  namespace: authentik
spec:
  releaseName: authentik
  chart:
    spec:
      chart: authentik
      sourceRef:
        kind: HelmRepository
        name: authentik-repo
        namespace: authentik
      # https://github.com/goauthentik/authentik/issues/12646
      # skip 2024.12.2
      # chart is broken with Helm 3.18
      # https://github.com/goauthentik/helm/pull/356/commits/f1af007bb82b6e7e5ab7274d7e9ff8b650baf274
      version: "2025.6.4"
  interval: 1h0m0s
  values:
    authentik:
      # registry-proxy block-start
      outposts:
        container_image_base: cr.nathanv.app/ghcr.io/goauthentik/%(type)s:%(version)s
      # registry-proxy block-end
      email:
        use_tls: true
        from: Authentik <authentik@nvaughn.email>
    postgresql:
      enabled: true
      # registry-proxy block-start
      global:
        security:
          allowInsecureImages: true
      image:
        registry: cr.nathanv.app/docker.io
      # registry-proxy block-end
      primary:
        persistence:
          enabled: true
          size: 1Gi
      defaultStorageClass: longhorn
    redis:
      enabled: true
      # registry-proxy block-start
      global:
        security:
          allowInsecureImages: true
      image:
        registry: cr.nathanv.app/docker.io
      # registry-proxy block-end
      master:
        persistence:
          enabled: true
          size: 1Gi
      defaultStorageClass: longhorn
    server:
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
      # required for icon uploads
      initContainers:
        - name: permission-fix
          # registry-proxy image-prefix
          image: cr.nathanv.app/docker.io/library/busybox:1.37.0
          command: ['sh', '-c']
          # https://docs.goauthentik.io/docs/troubleshooting/image_upload
          args: ['chown -R 1000:1000 /media && chmod ug+rwx media/']
          volumeMounts:
            - mountPath: /media
              name: media-vol
      volumes:
        - name: media-vol
          persistentVolumeClaim:
            claimName: authentik-pvc-media
      volumeMounts:
        - mountPath: /media
          name: media-vol
    global:
      # registry-proxy block-start
      image:
        repository: cr.nathanv.app/ghcr.io/goauthentik/server
      # registry-proxy block-end
      nodeSelector:
        role: apps
  valuesFrom:
    - kind: Secret
      name: authentik-secrets
      valuesKey: authentik.secret_key
      targetPath: authentik.secret_key
    - kind: Secret
      name: authentik-secrets
      valuesKey: authentik.postgresql.password
      targetPath: authentik.postgresql.password
    - kind: Secret
      name: authentik-secrets
      valuesKey: postgresql.auth.password
      targetPath: postgresql.auth.password
    - kind: Secret
      name: authentik-secrets
      valuesKey: authentik.email.host
      targetPath: authentik.email.host
    - kind: Secret
      name: authentik-secrets
      valuesKey: authentik.email.username
      targetPath: authentik.email.username
    - kind: Secret
      name: authentik-secrets
      valuesKey: authentik.email.password
      targetPath: authentik.email.password
