apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik-release
  namespace: authentik
spec:
  releaseName: authentik
  chart:
    spec:
      chart: authentik
      sourceRef:
        kind: HelmRepository
        name: authentik-repo
        namespace: authentik
      # https://github.com/goauthentik/authentik/issues/12646
      version: "2024.12.2"
  interval: 1h0m0s
  values:
    authentik:
      email:
        use_tls: true
        from: Authentik <authentik@nvaughn.email>
    postgresql:
      enabled: true
      persistence:
        enabled: true
      defaultStorageClass: longhorn
    redis:
      enabled: true
      persistence:
        enabled: true
      defaultStorageClass: longhorn
    global:
      nodeSelector:
        role: apps
  valuesFrom:
  - kind: Secret
    name: authentik-secrets
    valuesKey: authentik.secret_key
    targetPath: authentik.secret_key
  - kind: Secret
    name: authentik-secrets
    valuesKey: authentik.postgresql.password
    targetPath: authentik.postgresql.password
  - kind: Secret
    name: authentik-secrets
    valuesKey: postgresql.auth.password
    targetPath: postgresql.auth.password
  - kind: Secret
    name: authentik-secrets
    valuesKey: authentik.email.host
    targetPath: authentik.email.host
  - kind: Secret
    name: authentik-secrets
    valuesKey: authentik.email.username
    targetPath: authentik.email.username
  - kind: Secret
    name: authentik-secrets
    valuesKey: authentik.email.password
    targetPath: authentik.email.password
