apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik-release
  namespace: authentik
spec:
  releaseName: authentik
  chart:
    spec:
      chart: authentik
      sourceRef:
        kind: HelmRepository
        name: authentik-repo
        namespace: authentik
      # https://github.com/goauthentik/authentik/issues/12646
      version: "2024.12.2"
  interval: 1h0m0s
  values:
    authentik:
      email:
        use_tls: true
        from: Authentik <authentik@nvaughn.email>
    postgresql:
      enabled: true
      primary:
        persistence:
          enabled: true
          size: 1Gi
      defaultStorageClass: longhorn
    redis:
      enabled: true
      master:
        persistence:
          enabled: true
          size: 1Gi
      defaultStorageClass: longhorn
    server:
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
      # required for icon uploads
      initContainers:
        - name: permission-fix
          image: docker.io/library/busybox:1.37.0
          command: ['sh', '-c']
          # https://docs.goauthentik.io/docs/troubleshooting/image_upload
          args: ['chown -R 1000:1000 /media && chmod ug+rwx media/']
          volumeMounts:
            - mountPath: /media
              name: media-vol
      volumes:
        - name: media-vol
          persistentVolumeClaim:
            claimName: authentik-pvc-media
      volumeMounts:
        - mountPath: /media
          name: media-vol
    global:
      nodeSelector:
        role: apps
  valuesFrom:
    - kind: Secret
      name: authentik-secrets
      valuesKey: authentik.secret_key
      targetPath: authentik.secret_key
    - kind: Secret
      name: authentik-secrets
      valuesKey: authentik.postgresql.password
      targetPath: authentik.postgresql.password
    - kind: Secret
      name: authentik-secrets
      valuesKey: postgresql.auth.password
      targetPath: postgresql.auth.password
    - kind: Secret
      name: authentik-secrets
      valuesKey: authentik.email.host
      targetPath: authentik.email.host
    - kind: Secret
      name: authentik-secrets
      valuesKey: authentik.email.username
      targetPath: authentik.email.username
    - kind: Secret
      name: authentik-secrets
      valuesKey: authentik.email.password
      targetPath: authentik.email.password
