apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: stirling-pdf-env
  namespace: stirling-pdf
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: stirling-pdf-env
  data:
    - secretKey: SECURITY_OAUTH2_CLIENTID
      remoteRef:
        key: STIRLING_PDF_OIDC_CLIENT_ID
    - secretKey: SECURITY_OAUTH2_CLIENTSECRET
      remoteRef:
        key: STIRLING_PDF_OIDC_CLIENT_SECRET
