apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stirling-pdf-pvc-configs
  namespace: stirling-pdf
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
