apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stirling-pdf-pvc-ocr
  namespace: stirling-pdf
spec:
  storageClassName: longhorn-rwx
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
