apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: stirling-pdf-pvc
    namespace: stirling-pdf
spec:
    accessModes:
      - ReadWriteOnce
    resources:
        requests:
            storage: 5Gi
