apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy-release
  namespace: alloy
spec:
  releaseName: alloy
  chart:
    spec:
      chart: alloy
      sourceRef:
        kind: HelmRepository
        name: alloy-repo
        namespace: alloy
      version: "1.2.0"
  interval: 1h0m0s
  values:
    # registry-proxy block-start
    global:
      imageRegistry: cr.nathanv.app/docker.io
    # registry-proxy block-end
    alloy:
      mounts:
        varlog: true
        dockercontainers: true
      securityContext:
        privileged: true
        runAsUser: 0
      configMap:
        content: |
          discovery.kubernetes "pods" {
            role = "pod"
          }

          loki.source.kubernetes "pods" {
            targets    = discovery.kubernetes.pods.targets
            forward_to = [loki.write.loki.receiver]
          }

          loki.write "loki" {
              endpoint {
                  url = "http://loki-service.loki.svc.cluster.local:3100/loki/api/v1/push"
              }
          }
    serviceMonitor:
      enabled: true
