apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bookstack-mysql-deployment
  namespace: bookstack
spec:
  replicas: 1
  serviceName: bookstack-mysql
  selector:
    matchLabels:
      app: bookstack-mysql
  template:
    metadata:
      labels:
        app: bookstack-mysql
    spec:
      nodeSelector:
        role: apps
      initContainers:
        - name: lost-found-fix
          # registry-proxy image-prefix
          image: cr.nathanv.app/docker.io/library/busybox:1.37.0
          command: ['sh', '-c']
          args: ['rm -rf /var/lib/mysql/lost+found']
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-vol
      containers:
        - env:
            - name: MARIADB_RANDOM_ROOT_PASSWORD
              value: "1"
            - name: MARIADB_USER
              value: bookstack
            - name: MARIADB_DATABASE
              value: bookstack
          envFrom:
            - secretRef:
                name: bookstack-env
          # registry-proxy image-prefix
          image: cr.nathanv.app/docker.io/library/mariadb:11.8.2
          name: mariadb
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-vol
      volumes:
        - name: mysql-vol
          persistentVolumeClaim:
            claimName: bookstack-pvc-mysql
