apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bookstack-db-env
  namespace: bookstack
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: bookstack-db-env
  data:
    - secretKey: MARIADB_DATABASE
      remoteRef:
        key: BOOKSTACK_DB_DATABASE
    - secretKey: MARIADB_USER
      remoteRef:
        key: BOOKSTACK_DB_USERNAME
    - secretKey: MARIADB_PASSWORD
      remoteRef:
        key: BOOKSTACK_DB_PASSWORD
