apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: bookstack-pvc-bookstack
    namespace: bookstack
spec:
    storageClassName: longhorn
    accessModes:
      - ReadWriteOnce
    resources:
        requests:
            storage: 5Gi
