apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookstack-pvc-mysql
  namespace: bookstack
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
