apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookstack-pvc-bookstack
  namespace: bookstack
spec:
  storageClassName: longhorn-rwx
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
