apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lubelogger-app-env
  namespace: lubelogger
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: lubelogger-app-env
    template:
      mergePolicy: Merge
      data:
        POSTGRES_CONNECTION: "Host=lubelogger-postgresql-service.lubelogger.svc.cluster.local:5432;Username={{ .POSTGRES_USER }};Password={{ .POSTGRES_PASSWORD }};Database={{ .POSTGRES_DB }};"
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: LUBELOGGER_DB_PASSWORD
    - secretKey: POSTGRES_USER
      remoteRef:
        key: LUBELOGGER_DB_USERNAME
    - secretKey: POSTGRES_DB
      remoteRef:
        key: LUBELOGGER_DB_DATABASE
    - secretKey: MailConfig__EmailServer
      remoteRef:
        key: LUBELOGGER_SMTP_HOST
    - secretKey: MailConfig__Username
      remoteRef:
        key: LUBELOGGER_SMTP_USERNAME
    - secretKey: MailConfig__Password
      remoteRef:
        key: LUBELOGGER_SMTP_PASSWORD
    - secretKey: OpenIDConfig__ClientId
      remoteRef:
        key: LUBELOGGER_OIDC_CLIENT_ID
    - secretKey: OpenIDConfig__ClientSecret
      remoteRef:
        key: LUBELOGGER_OIDC_CLIENT_SECRET
