apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: lubelogger-route
  namespace: lubelogger
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`lubelogger.nathanv.app`)
      kind: Rule
      services:
        - name: lubelogger-service
          port: 8080
  tls:
    certResolver: le
    domains:
      - sans:
          - "*.nathanv.app"
