apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: lubelogger-route
  namespace: lubelogger
  annotations:
    k8s-dns.nathanv.me/hostname: lubelogger.nathanv.app
    k8s-dns.nathanv.me/external: tunnel.nathanv.app
    k8s-dns.nathanv.me/internal: reverse-proxy.svc.nathanv.home
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`lubelogger.nathanv.app`)
    kind: Rule
    services:
    - name: lubelogger-service
      port: 80
  tls:
    certResolver: le
    domains:
    - sans:
      - "*.nathanv.app"
