apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lubelogger-pvc-data
  namespace: lubelogger
spec:
  storageClassName: longhorn-rwx
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
