apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lubelogger-pvc-keys
  namespace: lubelogger
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
