apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lubelogger-pvc-keys
  namespace: lubelogger
spec:
  storageClassName: longhorn-rwx
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
