apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: lubelogger-release
    namespace: lubelogger
spec:
    releaseName: lubelogger
    chart:
        spec:
            chart: lubelogger
            sourceRef:
                kind: HelmRepository
                name: lubelogger-repo
                namespace: lubelogger
            version: "0.5.3"
    interval: 1h0m0s
    values:
        nodeSelector:
            role: apps
        persistence:
            data:
                enabled: true
                storageClass: longhorn
            documents:
                enabled: true
                storageClass: longhorn
            images:
                enabled: true
                storageClass: longhorn
        config:
            UseDarkMode: true
        # postgres is optional and it can use litedb internally instead.
